/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Adres
    /// </summary>
    [DataContract(Name = "Adres")]
    public partial class Adres : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Adres" /> class.
        /// </summary>
        /// <param name="adresNumarasiUAVT">adresNumarasiUAVT.</param>
        /// <param name="beldeBucak">beldeBucak.</param>
        /// <param name="caddeSokak">caddeSokak.</param>
        /// <param name="disKapiNo">disKapiNo.</param>
        /// <param name="icKapiNumarasi">icKapiNumarasi.</param>
        /// <param name="ilAdi">ilAdi.</param>
        /// <param name="ilKodu">ilKodu.</param>
        /// <param name="ilceAdi">ilceAdi.</param>
        /// <param name="ilceKodu">ilceKodu.</param>
        /// <param name="koy">koy.</param>
        /// <param name="mahalleSemt">mahalleSemt.</param>
        public Adres(string adresNumarasiUAVT = default(string), string beldeBucak = default(string), string caddeSokak = default(string), string disKapiNo = default(string), string icKapiNumarasi = default(string), string ilAdi = default(string), string ilKodu = default(string), string ilceAdi = default(string), string ilceKodu = default(string), string koy = default(string), string mahalleSemt = default(string))
        {
            this.AdresNumarasiUAVT = adresNumarasiUAVT;
            this.BeldeBucak = beldeBucak;
            this.CaddeSokak = caddeSokak;
            this.DisKapiNo = disKapiNo;
            this.IcKapiNumarasi = icKapiNumarasi;
            this.IlAdi = ilAdi;
            this.IlKodu = ilKodu;
            this.IlceAdi = ilceAdi;
            this.IlceKodu = ilceKodu;
            this.Koy = koy;
            this.MahalleSemt = mahalleSemt;
        }

        /// <summary>
        /// Gets or Sets AdresNumarasiUAVT
        /// </summary>
        [DataMember(Name = "adresNumarasiUAVT", EmitDefaultValue = true)]
        public string AdresNumarasiUAVT { get; set; }

        /// <summary>
        /// Gets or Sets BeldeBucak
        /// </summary>
        [DataMember(Name = "beldeBucak", EmitDefaultValue = true)]
        public string BeldeBucak { get; set; }

        /// <summary>
        /// Gets or Sets CaddeSokak
        /// </summary>
        [DataMember(Name = "caddeSokak", EmitDefaultValue = true)]
        public string CaddeSokak { get; set; }

        /// <summary>
        /// Gets or Sets DisKapiNo
        /// </summary>
        [DataMember(Name = "disKapiNo", EmitDefaultValue = true)]
        public string DisKapiNo { get; set; }

        /// <summary>
        /// Gets or Sets IcKapiNumarasi
        /// </summary>
        [DataMember(Name = "icKapiNumarasi", EmitDefaultValue = true)]
        public string IcKapiNumarasi { get; set; }

        /// <summary>
        /// Gets or Sets IlAdi
        /// </summary>
        [DataMember(Name = "ilAdi", EmitDefaultValue = true)]
        public string IlAdi { get; set; }

        /// <summary>
        /// Gets or Sets IlKodu
        /// </summary>
        [DataMember(Name = "ilKodu", EmitDefaultValue = true)]
        public string IlKodu { get; set; }

        /// <summary>
        /// Gets or Sets IlceAdi
        /// </summary>
        [DataMember(Name = "ilceAdi", EmitDefaultValue = true)]
        public string IlceAdi { get; set; }

        /// <summary>
        /// Gets or Sets IlceKodu
        /// </summary>
        [DataMember(Name = "ilceKodu", EmitDefaultValue = true)]
        public string IlceKodu { get; set; }

        /// <summary>
        /// Gets or Sets Koy
        /// </summary>
        [DataMember(Name = "koy", EmitDefaultValue = true)]
        public string Koy { get; set; }

        /// <summary>
        /// Gets or Sets MahalleSemt
        /// </summary>
        [DataMember(Name = "mahalleSemt", EmitDefaultValue = true)]
        public string MahalleSemt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Adres {\n");
            sb.Append("  AdresNumarasiUAVT: ").Append(AdresNumarasiUAVT).Append("\n");
            sb.Append("  BeldeBucak: ").Append(BeldeBucak).Append("\n");
            sb.Append("  CaddeSokak: ").Append(CaddeSokak).Append("\n");
            sb.Append("  DisKapiNo: ").Append(DisKapiNo).Append("\n");
            sb.Append("  IcKapiNumarasi: ").Append(IcKapiNumarasi).Append("\n");
            sb.Append("  IlAdi: ").Append(IlAdi).Append("\n");
            sb.Append("  IlKodu: ").Append(IlKodu).Append("\n");
            sb.Append("  IlceAdi: ").Append(IlceAdi).Append("\n");
            sb.Append("  IlceKodu: ").Append(IlceKodu).Append("\n");
            sb.Append("  Koy: ").Append(Koy).Append("\n");
            sb.Append("  MahalleSemt: ").Append(MahalleSemt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
