/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BpmCekListe
    /// </summary>
    [DataContract(Name = "BpmCekListe")]
    public partial class BpmCekListe : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BpmCekListe" /> class.
        /// </summary>
        /// <param name="islemReferansNo">islemReferansNo.</param>
        /// <param name="belgeReferansNo">belgeReferansNo.</param>
        /// <param name="devirReferansNo">devirReferansNo.</param>
        /// <param name="odemeAraciReferansNo">odemeAraciReferansNo.</param>
        /// <param name="belgeNumarasi">belgeNumarasi.</param>
        /// <param name="isSuccess">isSuccess.</param>
        /// <param name="isCancel">isCancel.</param>
        /// <param name="hataListesi">hataListesi.</param>
        public BpmCekListe(string islemReferansNo = default(string), string belgeReferansNo = default(string), List<string> devirReferansNo = default(List<string>), string odemeAraciReferansNo = default(string), string belgeNumarasi = default(string), string isSuccess = default(string), string isCancel = default(string), List<UyariListe> hataListesi = default(List<UyariListe>))
        {
            this.IslemReferansNo = islemReferansNo;
            this.BelgeReferansNo = belgeReferansNo;
            this.DevirReferansNo = devirReferansNo;
            this.OdemeAraciReferansNo = odemeAraciReferansNo;
            this.BelgeNumarasi = belgeNumarasi;
            this.IsSuccess = isSuccess;
            this.IsCancel = isCancel;
            this.HataListesi = hataListesi;
        }

        /// <summary>
        /// Gets or Sets IslemReferansNo
        /// </summary>
        [DataMember(Name = "islemReferansNo", EmitDefaultValue = true)]
        public string IslemReferansNo { get; set; }

        /// <summary>
        /// Gets or Sets BelgeReferansNo
        /// </summary>
        [DataMember(Name = "belgeReferansNo", EmitDefaultValue = true)]
        public string BelgeReferansNo { get; set; }

        /// <summary>
        /// Gets or Sets DevirReferansNo
        /// </summary>
        [DataMember(Name = "devirReferansNo", EmitDefaultValue = true)]
        public List<string> DevirReferansNo { get; set; }

        /// <summary>
        /// Gets or Sets OdemeAraciReferansNo
        /// </summary>
        [DataMember(Name = "odemeAraciReferansNo", EmitDefaultValue = true)]
        public string OdemeAraciReferansNo { get; set; }

        /// <summary>
        /// Gets or Sets BelgeNumarasi
        /// </summary>
        [DataMember(Name = "belgeNumarasi", EmitDefaultValue = true)]
        public string BelgeNumarasi { get; set; }

        /// <summary>
        /// Gets or Sets IsSuccess
        /// </summary>
        [DataMember(Name = "isSuccess", EmitDefaultValue = true)]
        public string IsSuccess { get; set; }

        /// <summary>
        /// Gets or Sets IsCancel
        /// </summary>
        [DataMember(Name = "isCancel", EmitDefaultValue = true)]
        public string IsCancel { get; set; }

        /// <summary>
        /// Gets or Sets HataListesi
        /// </summary>
        [DataMember(Name = "hataListesi", EmitDefaultValue = true)]
        public List<UyariListe> HataListesi { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BpmCekListe {\n");
            sb.Append("  IslemReferansNo: ").Append(IslemReferansNo).Append("\n");
            sb.Append("  BelgeReferansNo: ").Append(BelgeReferansNo).Append("\n");
            sb.Append("  DevirReferansNo: ").Append(DevirReferansNo).Append("\n");
            sb.Append("  OdemeAraciReferansNo: ").Append(OdemeAraciReferansNo).Append("\n");
            sb.Append("  BelgeNumarasi: ").Append(BelgeNumarasi).Append("\n");
            sb.Append("  IsSuccess: ").Append(IsSuccess).Append("\n");
            sb.Append("  IsCancel: ").Append(IsCancel).Append("\n");
            sb.Append("  HataListesi: ").Append(HataListesi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
