/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BpmDevirListe
    /// </summary>
    [DataContract(Name = "BpmDevirListe")]
    public partial class BpmDevirListe : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BpmDevirListe" /> class.
        /// </summary>
        /// <param name="belgeSeriNo">belgeSeriNo.</param>
        /// <param name="belgeSiraNo">belgeSiraNo.</param>
        /// <param name="islemSonucu">islemSonucu.</param>
        /// <param name="islemReferansNo">islemReferansNo.</param>
        /// <param name="belgeReferansNo">belgeReferansNo.</param>
        /// <param name="kalanTutar">kalanTutar.</param>
        /// <param name="artanTutar">artanTutar.</param>
        /// <param name="belgeTutari">belgeTutari.</param>
        /// <param name="belgeKurOrani">belgeKurOrani.</param>
        /// <param name="devirTutari">devirTutari.</param>
        /// <param name="dovizKodu">dovizKodu.</param>
        /// <param name="aliciTckn">aliciTckn.</param>
        /// <param name="saticiUnvan">saticiUnvan.</param>
        /// <param name="saticiTckn">saticiTckn.</param>
        /// <param name="isSuccess">isSuccess.</param>
        /// <param name="isCancel">isCancel.</param>
        /// <param name="hataListesi">hataListesi.</param>
        public BpmDevirListe(string belgeSeriNo = default(string), string belgeSiraNo = default(string), string islemSonucu = default(string), string islemReferansNo = default(string), string belgeReferansNo = default(string), double kalanTutar = default(double), double artanTutar = default(double), double belgeTutari = default(double), double belgeKurOrani = default(double), double devirTutari = default(double), string dovizKodu = default(string), string aliciTckn = default(string), string saticiUnvan = default(string), string saticiTckn = default(string), string isSuccess = default(string), string isCancel = default(string), List<UyariListe> hataListesi = default(List<UyariListe>))
        {
            this.BelgeSeriNo = belgeSeriNo;
            this.BelgeSiraNo = belgeSiraNo;
            this.IslemSonucu = islemSonucu;
            this.IslemReferansNo = islemReferansNo;
            this.BelgeReferansNo = belgeReferansNo;
            this.KalanTutar = kalanTutar;
            this.ArtanTutar = artanTutar;
            this.BelgeTutari = belgeTutari;
            this.BelgeKurOrani = belgeKurOrani;
            this.DevirTutari = devirTutari;
            this.DovizKodu = dovizKodu;
            this.AliciTckn = aliciTckn;
            this.SaticiUnvan = saticiUnvan;
            this.SaticiTckn = saticiTckn;
            this.IsSuccess = isSuccess;
            this.IsCancel = isCancel;
            this.HataListesi = hataListesi;
        }

        /// <summary>
        /// Gets or Sets BelgeSeriNo
        /// </summary>
        [DataMember(Name = "belgeSeriNo", EmitDefaultValue = true)]
        public string BelgeSeriNo { get; set; }

        /// <summary>
        /// Gets or Sets BelgeSiraNo
        /// </summary>
        [DataMember(Name = "belgeSiraNo", EmitDefaultValue = true)]
        public string BelgeSiraNo { get; set; }

        /// <summary>
        /// Gets or Sets IslemSonucu
        /// </summary>
        [DataMember(Name = "islemSonucu", EmitDefaultValue = true)]
        public string IslemSonucu { get; set; }

        /// <summary>
        /// Gets or Sets IslemReferansNo
        /// </summary>
        [DataMember(Name = "islemReferansNo", EmitDefaultValue = true)]
        public string IslemReferansNo { get; set; }

        /// <summary>
        /// Gets or Sets BelgeReferansNo
        /// </summary>
        [DataMember(Name = "belgeReferansNo", EmitDefaultValue = true)]
        public string BelgeReferansNo { get; set; }

        /// <summary>
        /// Gets or Sets KalanTutar
        /// </summary>
        [DataMember(Name = "kalanTutar", EmitDefaultValue = false)]
        public double KalanTutar { get; set; }

        /// <summary>
        /// Gets or Sets ArtanTutar
        /// </summary>
        [DataMember(Name = "artanTutar", EmitDefaultValue = false)]
        public double ArtanTutar { get; set; }

        /// <summary>
        /// Gets or Sets BelgeTutari
        /// </summary>
        [DataMember(Name = "belgeTutari", EmitDefaultValue = false)]
        public double BelgeTutari { get; set; }

        /// <summary>
        /// Gets or Sets BelgeKurOrani
        /// </summary>
        [DataMember(Name = "belgeKurOrani", EmitDefaultValue = false)]
        public double BelgeKurOrani { get; set; }

        /// <summary>
        /// Gets or Sets DevirTutari
        /// </summary>
        [DataMember(Name = "devirTutari", EmitDefaultValue = false)]
        public double DevirTutari { get; set; }

        /// <summary>
        /// Gets or Sets DovizKodu
        /// </summary>
        [DataMember(Name = "dovizKodu", EmitDefaultValue = true)]
        public string DovizKodu { get; set; }

        /// <summary>
        /// Gets or Sets AliciTckn
        /// </summary>
        [DataMember(Name = "aliciTckn", EmitDefaultValue = true)]
        public string AliciTckn { get; set; }

        /// <summary>
        /// Gets or Sets SaticiUnvan
        /// </summary>
        [DataMember(Name = "saticiUnvan", EmitDefaultValue = true)]
        public string SaticiUnvan { get; set; }

        /// <summary>
        /// Gets or Sets SaticiTckn
        /// </summary>
        [DataMember(Name = "saticiTckn", EmitDefaultValue = true)]
        public string SaticiTckn { get; set; }

        /// <summary>
        /// Gets or Sets IsSuccess
        /// </summary>
        [DataMember(Name = "isSuccess", EmitDefaultValue = true)]
        public string IsSuccess { get; set; }

        /// <summary>
        /// Gets or Sets IsCancel
        /// </summary>
        [DataMember(Name = "isCancel", EmitDefaultValue = true)]
        public string IsCancel { get; set; }

        /// <summary>
        /// Gets or Sets HataListesi
        /// </summary>
        [DataMember(Name = "hataListesi", EmitDefaultValue = true)]
        public List<UyariListe> HataListesi { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BpmDevirListe {\n");
            sb.Append("  BelgeSeriNo: ").Append(BelgeSeriNo).Append("\n");
            sb.Append("  BelgeSiraNo: ").Append(BelgeSiraNo).Append("\n");
            sb.Append("  IslemSonucu: ").Append(IslemSonucu).Append("\n");
            sb.Append("  IslemReferansNo: ").Append(IslemReferansNo).Append("\n");
            sb.Append("  BelgeReferansNo: ").Append(BelgeReferansNo).Append("\n");
            sb.Append("  KalanTutar: ").Append(KalanTutar).Append("\n");
            sb.Append("  ArtanTutar: ").Append(ArtanTutar).Append("\n");
            sb.Append("  BelgeTutari: ").Append(BelgeTutari).Append("\n");
            sb.Append("  BelgeKurOrani: ").Append(BelgeKurOrani).Append("\n");
            sb.Append("  DevirTutari: ").Append(DevirTutari).Append("\n");
            sb.Append("  DovizKodu: ").Append(DovizKodu).Append("\n");
            sb.Append("  AliciTckn: ").Append(AliciTckn).Append("\n");
            sb.Append("  SaticiUnvan: ").Append(SaticiUnvan).Append("\n");
            sb.Append("  SaticiTckn: ").Append(SaticiTckn).Append("\n");
            sb.Append("  IsSuccess: ").Append(IsSuccess).Append("\n");
            sb.Append("  IsCancel: ").Append(IsCancel).Append("\n");
            sb.Append("  HataListesi: ").Append(HataListesi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
