/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BuyerLimitWatchDetailRequest
    /// </summary>
    [DataContract(Name = "BuyerLimitWatchDetailRequest")]
    public partial class BuyerLimitWatchDetailRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BuyerLimitWatchDetailRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BuyerLimitWatchDetailRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BuyerLimitWatchDetailRequest" /> class.
        /// </summary>
        /// <param name="tcknVkn">tcknVkn (required).</param>
        /// <param name="customerStatus">customerStatus (required).</param>
        public BuyerLimitWatchDetailRequest(string tcknVkn = default(string), string customerStatus = default(string))
        {
            // to ensure "tcknVkn" is required (not null)
            if (tcknVkn == null)
            {
                throw new ArgumentNullException("tcknVkn is a required property for BuyerLimitWatchDetailRequest and cannot be null");
            }
            this.TcknVkn = tcknVkn;
            // to ensure "customerStatus" is required (not null)
            if (customerStatus == null)
            {
                throw new ArgumentNullException("customerStatus is a required property for BuyerLimitWatchDetailRequest and cannot be null");
            }
            this.CustomerStatus = customerStatus;
        }

        /// <summary>
        /// Gets or Sets TcknVkn
        /// </summary>
        [DataMember(Name = "tcknVkn", IsRequired = true, EmitDefaultValue = true)]
        public string TcknVkn { get; set; }

        /// <summary>
        /// Gets or Sets CustomerStatus
        /// </summary>
        [DataMember(Name = "customerStatus", IsRequired = true, EmitDefaultValue = true)]
        public string CustomerStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BuyerLimitWatchDetailRequest {\n");
            sb.Append("  TcknVkn: ").Append(TcknVkn).Append("\n");
            sb.Append("  CustomerStatus: ").Append(CustomerStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TcknVkn (string) minLength
            if (this.TcknVkn != null && this.TcknVkn.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TcknVkn, length must be greater than 1.", new [] { "TcknVkn" });
            }

            // CustomerStatus (string) minLength
            if (this.CustomerStatus != null && this.CustomerStatus.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CustomerStatus, length must be greater than 1.", new [] { "CustomerStatus" });
            }

            yield break;
        }
    }

}
