/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CaprazCekIliskileriSorguResponse
    /// </summary>
    [DataContract(Name = "caprazCekIliskileriSorguResponse")]
    public partial class CaprazCekIliskileriSorguResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CaprazCekIliskileriSorguResponse" /> class.
        /// </summary>
        /// <param name="referansNo">referansNo.</param>
        /// <param name="data">data.</param>
        /// <param name="automaticallyResult">automaticallyResult.</param>
        /// <param name="errors">errors.</param>
        /// <param name="kesidecicaprazceksorgututar">kesidecicaprazceksorgututar.</param>
        /// <param name="soncirantacaprazceksorgututar">soncirantacaprazceksorgututar.</param>
        /// <param name="saticiilecapraziliski">saticiilecapraziliski.</param>
        public CaprazCekIliskileriSorguResponse(string referansNo = default(string), List<CaprazCekIliskileriBean> data = default(List<CaprazCekIliskileriBean>), string automaticallyResult = default(string), IslemResponse errors = default(IslemResponse), double kesidecicaprazceksorgututar = default(double), double soncirantacaprazceksorgututar = default(double), string saticiilecapraziliski = default(string))
        {
            this.ReferansNo = referansNo;
            this.Data = data;
            this.AutomaticallyResult = automaticallyResult;
            this.Errors = errors;
            this.Kesidecicaprazceksorgututar = kesidecicaprazceksorgututar;
            this.Soncirantacaprazceksorgututar = soncirantacaprazceksorgututar;
            this.Saticiilecapraziliski = saticiilecapraziliski;
        }

        /// <summary>
        /// Gets or Sets ReferansNo
        /// </summary>
        [DataMember(Name = "ReferansNo", EmitDefaultValue = true)]
        public string ReferansNo { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "Data", EmitDefaultValue = true)]
        public List<CaprazCekIliskileriBean> Data { get; set; }

        /// <summary>
        /// Gets or Sets AutomaticallyResult
        /// </summary>
        [DataMember(Name = "AutomaticallyResult", EmitDefaultValue = true)]
        public string AutomaticallyResult { get; set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "Errors", EmitDefaultValue = false)]
        public IslemResponse Errors { get; set; }

        /// <summary>
        /// Gets or Sets Kesidecicaprazceksorgututar
        /// </summary>
        [DataMember(Name = "kesidecicaprazceksorgututar", EmitDefaultValue = false)]
        public double Kesidecicaprazceksorgututar { get; set; }

        /// <summary>
        /// Gets or Sets Soncirantacaprazceksorgututar
        /// </summary>
        [DataMember(Name = "soncirantacaprazceksorgututar", EmitDefaultValue = false)]
        public double Soncirantacaprazceksorgututar { get; set; }

        /// <summary>
        /// Gets or Sets Saticiilecapraziliski
        /// </summary>
        [DataMember(Name = "saticiilecapraziliski", EmitDefaultValue = true)]
        public string Saticiilecapraziliski { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CaprazCekIliskileriSorguResponse {\n");
            sb.Append("  ReferansNo: ").Append(ReferansNo).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  AutomaticallyResult: ").Append(AutomaticallyResult).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Kesidecicaprazceksorgututar: ").Append(Kesidecicaprazceksorgututar).Append("\n");
            sb.Append("  Soncirantacaprazceksorgututar: ").Append(Soncirantacaprazceksorgututar).Append("\n");
            sb.Append("  Saticiilecapraziliski: ").Append(Saticiilecapraziliski).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
