/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CautionsSuffixProductEntity
    /// </summary>
    [DataContract(Name = "CautionsSuffixProductEntity")]
    public partial class CautionsSuffixProductEntity : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CautionsSuffixProductEntity" /> class.
        /// </summary>
        /// <param name="cautionCreditSuffix">cautionCreditSuffix.</param>
        /// <param name="creditType">creditType.</param>
        /// <param name="superProductCode">superProductCode.</param>
        /// <param name="productCode">productCode.</param>
        /// <param name="projectCode">projectCode.</param>
        /// <param name="campaignCode">campaignCode.</param>
        /// <param name="cautionCurrencyType">cautionCurrencyType.</param>
        /// <param name="cautionCreditProductAmount">cautionCreditProductAmount.</param>
        public CautionsSuffixProductEntity(int cautionCreditSuffix = default(int), string creditType = default(string), string superProductCode = default(string), string productCode = default(string), string projectCode = default(string), string campaignCode = default(string), string cautionCurrencyType = default(string), double cautionCreditProductAmount = default(double))
        {
            this.CautionCreditSuffix = cautionCreditSuffix;
            this.CreditType = creditType;
            this.SuperProductCode = superProductCode;
            this.ProductCode = productCode;
            this.ProjectCode = projectCode;
            this.CampaignCode = campaignCode;
            this.CautionCurrencyType = cautionCurrencyType;
            this.CautionCreditProductAmount = cautionCreditProductAmount;
        }

        /// <summary>
        /// Gets or Sets CautionCreditSuffix
        /// </summary>
        [DataMember(Name = "CautionCreditSuffix", EmitDefaultValue = false)]
        public int CautionCreditSuffix { get; set; }

        /// <summary>
        /// Gets or Sets CreditType
        /// </summary>
        [DataMember(Name = "CreditType", EmitDefaultValue = true)]
        public string CreditType { get; set; }

        /// <summary>
        /// Gets or Sets SuperProductCode
        /// </summary>
        [DataMember(Name = "SuperProductCode", EmitDefaultValue = true)]
        public string SuperProductCode { get; set; }

        /// <summary>
        /// Gets or Sets ProductCode
        /// </summary>
        [DataMember(Name = "ProductCode", EmitDefaultValue = true)]
        public string ProductCode { get; set; }

        /// <summary>
        /// Gets or Sets ProjectCode
        /// </summary>
        [DataMember(Name = "ProjectCode", EmitDefaultValue = true)]
        public string ProjectCode { get; set; }

        /// <summary>
        /// Gets or Sets CampaignCode
        /// </summary>
        [DataMember(Name = "CampaignCode", EmitDefaultValue = true)]
        public string CampaignCode { get; set; }

        /// <summary>
        /// Gets or Sets CautionCurrencyType
        /// </summary>
        [DataMember(Name = "CautionCurrencyType", EmitDefaultValue = true)]
        public string CautionCurrencyType { get; set; }

        /// <summary>
        /// Gets or Sets CautionCreditProductAmount
        /// </summary>
        [DataMember(Name = "CautionCreditProductAmount", EmitDefaultValue = false)]
        public double CautionCreditProductAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CautionsSuffixProductEntity {\n");
            sb.Append("  CautionCreditSuffix: ").Append(CautionCreditSuffix).Append("\n");
            sb.Append("  CreditType: ").Append(CreditType).Append("\n");
            sb.Append("  SuperProductCode: ").Append(SuperProductCode).Append("\n");
            sb.Append("  ProductCode: ").Append(ProductCode).Append("\n");
            sb.Append("  ProjectCode: ").Append(ProjectCode).Append("\n");
            sb.Append("  CampaignCode: ").Append(CampaignCode).Append("\n");
            sb.Append("  CautionCurrencyType: ").Append(CautionCurrencyType).Append("\n");
            sb.Append("  CautionCreditProductAmount: ").Append(CautionCreditProductAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
