/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CekKayitList
    /// </summary>
    [DataContract(Name = "cekKayitList")]
    public partial class CekKayitList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CekKayitList" /> class.
        /// </summary>
        /// <param name="qrMicr">qrMicr.</param>
        /// <param name="talepBaslangicZamani">talepBaslangicZamani.</param>
        /// <param name="talepBitisZamani">talepBitisZamani.</param>
        /// <param name="kaydedenVkn">kaydedenVkn.</param>
        /// <param name="kaydedenUnvan">kaydedenUnvan.</param>
        /// <param name="kesideciVkn">kesideciVkn.</param>
        /// <param name="kesideciUnvan">kesideciUnvan.</param>
        /// <param name="bankaEftKodu">bankaEftKodu.</param>
        /// <param name="subeKodu">subeKodu.</param>
        /// <param name="cekHesapNo">cekHesapNo.</param>
        /// <param name="cekSeriNo">cekSeriNo.</param>
        /// <param name="cekSiraNo">cekSiraNo.</param>
        /// <param name="cekVadeTarihi">cekVadeTarihi.</param>
        /// <param name="cekTutari">cekTutari.</param>
        /// <param name="cekTutariDovizCinsi">cekTutariDovizCinsi.</param>
        public CekKayitList(string qrMicr = default(string), string talepBaslangicZamani = default(string), string talepBitisZamani = default(string), string kaydedenVkn = default(string), string kaydedenUnvan = default(string), string kesideciVkn = default(string), string kesideciUnvan = default(string), string bankaEftKodu = default(string), string subeKodu = default(string), string cekHesapNo = default(string), string cekSeriNo = default(string), string cekSiraNo = default(string), string cekVadeTarihi = default(string), string cekTutari = default(string), string cekTutariDovizCinsi = default(string))
        {
            this.QrMicr = qrMicr;
            this.TalepBaslangicZamani = talepBaslangicZamani;
            this.TalepBitisZamani = talepBitisZamani;
            this.KaydedenVkn = kaydedenVkn;
            this.KaydedenUnvan = kaydedenUnvan;
            this.KesideciVkn = kesideciVkn;
            this.KesideciUnvan = kesideciUnvan;
            this.BankaEftKodu = bankaEftKodu;
            this.SubeKodu = subeKodu;
            this.CekHesapNo = cekHesapNo;
            this.CekSeriNo = cekSeriNo;
            this.CekSiraNo = cekSiraNo;
            this.CekVadeTarihi = cekVadeTarihi;
            this.CekTutari = cekTutari;
            this.CekTutariDovizCinsi = cekTutariDovizCinsi;
        }

        /// <summary>
        /// Gets or Sets QrMicr
        /// </summary>
        [DataMember(Name = "qrMicr", EmitDefaultValue = true)]
        public string QrMicr { get; set; }

        /// <summary>
        /// Gets or Sets TalepBaslangicZamani
        /// </summary>
        [DataMember(Name = "talepBaslangicZamani", EmitDefaultValue = true)]
        public string TalepBaslangicZamani { get; set; }

        /// <summary>
        /// Gets or Sets TalepBitisZamani
        /// </summary>
        [DataMember(Name = "talepBitisZamani", EmitDefaultValue = true)]
        public string TalepBitisZamani { get; set; }

        /// <summary>
        /// Gets or Sets KaydedenVkn
        /// </summary>
        [DataMember(Name = "kaydedenVkn", EmitDefaultValue = true)]
        public string KaydedenVkn { get; set; }

        /// <summary>
        /// Gets or Sets KaydedenUnvan
        /// </summary>
        [DataMember(Name = "kaydedenUnvan", EmitDefaultValue = true)]
        public string KaydedenUnvan { get; set; }

        /// <summary>
        /// Gets or Sets KesideciVkn
        /// </summary>
        [DataMember(Name = "kesideciVkn", EmitDefaultValue = true)]
        public string KesideciVkn { get; set; }

        /// <summary>
        /// Gets or Sets KesideciUnvan
        /// </summary>
        [DataMember(Name = "kesideciUnvan", EmitDefaultValue = true)]
        public string KesideciUnvan { get; set; }

        /// <summary>
        /// Gets or Sets BankaEftKodu
        /// </summary>
        [DataMember(Name = "bankaEftKodu", EmitDefaultValue = true)]
        public string BankaEftKodu { get; set; }

        /// <summary>
        /// Gets or Sets SubeKodu
        /// </summary>
        [DataMember(Name = "subeKodu", EmitDefaultValue = true)]
        public string SubeKodu { get; set; }

        /// <summary>
        /// Gets or Sets CekHesapNo
        /// </summary>
        [DataMember(Name = "cekHesapNo", EmitDefaultValue = true)]
        public string CekHesapNo { get; set; }

        /// <summary>
        /// Gets or Sets CekSeriNo
        /// </summary>
        [DataMember(Name = "cekSeriNo", EmitDefaultValue = true)]
        public string CekSeriNo { get; set; }

        /// <summary>
        /// Gets or Sets CekSiraNo
        /// </summary>
        [DataMember(Name = "cekSiraNo", EmitDefaultValue = true)]
        public string CekSiraNo { get; set; }

        /// <summary>
        /// Gets or Sets CekVadeTarihi
        /// </summary>
        [DataMember(Name = "cekVadeTarihi", EmitDefaultValue = true)]
        public string CekVadeTarihi { get; set; }

        /// <summary>
        /// Gets or Sets CekTutari
        /// </summary>
        [DataMember(Name = "cekTutari", EmitDefaultValue = true)]
        public string CekTutari { get; set; }

        /// <summary>
        /// Gets or Sets CekTutariDovizCinsi
        /// </summary>
        [DataMember(Name = "cekTutariDovizCinsi", EmitDefaultValue = true)]
        public string CekTutariDovizCinsi { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CekKayitList {\n");
            sb.Append("  QrMicr: ").Append(QrMicr).Append("\n");
            sb.Append("  TalepBaslangicZamani: ").Append(TalepBaslangicZamani).Append("\n");
            sb.Append("  TalepBitisZamani: ").Append(TalepBitisZamani).Append("\n");
            sb.Append("  KaydedenVkn: ").Append(KaydedenVkn).Append("\n");
            sb.Append("  KaydedenUnvan: ").Append(KaydedenUnvan).Append("\n");
            sb.Append("  KesideciVkn: ").Append(KesideciVkn).Append("\n");
            sb.Append("  KesideciUnvan: ").Append(KesideciUnvan).Append("\n");
            sb.Append("  BankaEftKodu: ").Append(BankaEftKodu).Append("\n");
            sb.Append("  SubeKodu: ").Append(SubeKodu).Append("\n");
            sb.Append("  CekHesapNo: ").Append(CekHesapNo).Append("\n");
            sb.Append("  CekSeriNo: ").Append(CekSeriNo).Append("\n");
            sb.Append("  CekSiraNo: ").Append(CekSiraNo).Append("\n");
            sb.Append("  CekVadeTarihi: ").Append(CekVadeTarihi).Append("\n");
            sb.Append("  CekTutari: ").Append(CekTutari).Append("\n");
            sb.Append("  CekTutariDovizCinsi: ").Append(CekTutariDovizCinsi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
