/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ChequeStatusResponse
    /// </summary>
    [DataContract(Name = "ChequeStatusResponse")]
    public partial class ChequeStatusResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChequeStatusResponse" /> class.
        /// </summary>
        /// <param name="islemReferansNumarasi">islemReferansNumarasi.</param>
        /// <param name="islemSonucu">islemSonucu.</param>
        /// <param name="cekDurumKodu">cekDurumKodu.</param>
        /// <param name="cekIbanNo">cekIbanNo.</param>
        /// <param name="cekYasaklisi">cekYasaklisi.</param>
        /// <param name="errors">errors.</param>
        /// <param name="cekKayitList">cekKayitList.</param>
        /// <param name="automaticallyResult">automaticallyResult.</param>
        public ChequeStatusResponse(string islemReferansNumarasi = default(string), string islemSonucu = default(string), string cekDurumKodu = default(string), string cekIbanNo = default(string), string cekYasaklisi = default(string), IslemResponse errors = default(IslemResponse), List<CekKayitList> cekKayitList = default(List<CekKayitList>), string automaticallyResult = default(string))
        {
            this.IslemReferansNumarasi = islemReferansNumarasi;
            this.IslemSonucu = islemSonucu;
            this.CekDurumKodu = cekDurumKodu;
            this.CekIbanNo = cekIbanNo;
            this.CekYasaklisi = cekYasaklisi;
            this.Errors = errors;
            this.CekKayitList = cekKayitList;
            this.AutomaticallyResult = automaticallyResult;
        }

        /// <summary>
        /// Gets or Sets IslemReferansNumarasi
        /// </summary>
        [DataMember(Name = "islemReferansNumarasi", EmitDefaultValue = true)]
        public string IslemReferansNumarasi { get; set; }

        /// <summary>
        /// Gets or Sets IslemSonucu
        /// </summary>
        [DataMember(Name = "islemSonucu", EmitDefaultValue = true)]
        public string IslemSonucu { get; set; }

        /// <summary>
        /// Gets or Sets CekDurumKodu
        /// </summary>
        [DataMember(Name = "cekDurumKodu", EmitDefaultValue = true)]
        public string CekDurumKodu { get; set; }

        /// <summary>
        /// Gets or Sets CekIbanNo
        /// </summary>
        [DataMember(Name = "cekIbanNo", EmitDefaultValue = true)]
        public string CekIbanNo { get; set; }

        /// <summary>
        /// Gets or Sets CekYasaklisi
        /// </summary>
        [DataMember(Name = "cekYasaklisi", EmitDefaultValue = true)]
        public string CekYasaklisi { get; set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public IslemResponse Errors { get; set; }

        /// <summary>
        /// Gets or Sets CekKayitList
        /// </summary>
        [DataMember(Name = "cekKayitList", EmitDefaultValue = true)]
        public List<CekKayitList> CekKayitList { get; set; }

        /// <summary>
        /// Gets or Sets AutomaticallyResult
        /// </summary>
        [DataMember(Name = "AutomaticallyResult", EmitDefaultValue = true)]
        public string AutomaticallyResult { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChequeStatusResponse {\n");
            sb.Append("  IslemReferansNumarasi: ").Append(IslemReferansNumarasi).Append("\n");
            sb.Append("  IslemSonucu: ").Append(IslemSonucu).Append("\n");
            sb.Append("  CekDurumKodu: ").Append(CekDurumKodu).Append("\n");
            sb.Append("  CekIbanNo: ").Append(CekIbanNo).Append("\n");
            sb.Append("  CekYasaklisi: ").Append(CekYasaklisi).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  CekKayitList: ").Append(CekKayitList).Append("\n");
            sb.Append("  AutomaticallyResult: ").Append(AutomaticallyResult).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
