/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DevirGuncelleFaturaEkGirdiParametre
    /// </summary>
    [DataContract(Name = "devirGuncelleFaturaEkGirdiParametre")]
    public partial class DevirGuncelleFaturaEkGirdiParametre : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DevirGuncelleFaturaEkGirdiParametre" /> class.
        /// </summary>
        /// <param name="gumrukBeyannameNoField">gumrukBeyannameNoField.</param>
        /// <param name="konsimentoNumarasiField">konsimentoNumarasiField.</param>
        /// <param name="yuklemeTarihiField">yuklemeTarihiField.</param>
        /// <param name="muhabirUnvanField">muhabirUnvanField.</param>
        /// <param name="sigortaSirketiUnvanField">sigortaSirketiUnvanField.</param>
        /// <param name="irsaliyeNumarasiField">irsaliyeNumarasiField.</param>
        /// <param name="irsaliyeTarihiField">irsaliyeTarihiField.</param>
        /// <param name="imalatciVergiNoField">imalatciVergiNoField.</param>
        /// <param name="eFaturaHashDegeriField">eFaturaHashDegeriField.</param>
        /// <param name="faturaXmlField">faturaXmlField.</param>
        /// <param name="faturamParaIdField">faturamParaIdField.</param>
        /// <param name="aliciNeviKimlikTipField">aliciNeviKimlikTipField.</param>
        /// <param name="aliciNeviKimlikNoField">aliciNeviKimlikNoField.</param>
        /// <param name="saticiNeviKimlikTipField">saticiNeviKimlikTipField.</param>
        /// <param name="saticiNeviKimlikNoField">saticiNeviKimlikNoField.</param>
        public DevirGuncelleFaturaEkGirdiParametre(string gumrukBeyannameNoField = default(string), string konsimentoNumarasiField = default(string), string yuklemeTarihiField = default(string), string muhabirUnvanField = default(string), string sigortaSirketiUnvanField = default(string), string irsaliyeNumarasiField = default(string), string irsaliyeTarihiField = default(string), string imalatciVergiNoField = default(string), string eFaturaHashDegeriField = default(string), byte[] faturaXmlField = default(byte[]), string faturamParaIdField = default(string), string aliciNeviKimlikTipField = default(string), string aliciNeviKimlikNoField = default(string), string saticiNeviKimlikTipField = default(string), string saticiNeviKimlikNoField = default(string))
        {
            this.GumrukBeyannameNoField = gumrukBeyannameNoField;
            this.KonsimentoNumarasiField = konsimentoNumarasiField;
            this.YuklemeTarihiField = yuklemeTarihiField;
            this.MuhabirUnvanField = muhabirUnvanField;
            this.SigortaSirketiUnvanField = sigortaSirketiUnvanField;
            this.IrsaliyeNumarasiField = irsaliyeNumarasiField;
            this.IrsaliyeTarihiField = irsaliyeTarihiField;
            this.ImalatciVergiNoField = imalatciVergiNoField;
            this.EFaturaHashDegeriField = eFaturaHashDegeriField;
            this.FaturaXmlField = faturaXmlField;
            this.FaturamParaIdField = faturamParaIdField;
            this.AliciNeviKimlikTipField = aliciNeviKimlikTipField;
            this.AliciNeviKimlikNoField = aliciNeviKimlikNoField;
            this.SaticiNeviKimlikTipField = saticiNeviKimlikTipField;
            this.SaticiNeviKimlikNoField = saticiNeviKimlikNoField;
        }

        /// <summary>
        /// Gets or Sets GumrukBeyannameNoField
        /// </summary>
        [DataMember(Name = "gumrukBeyannameNoField", EmitDefaultValue = true)]
        public string GumrukBeyannameNoField { get; set; }

        /// <summary>
        /// Gets or Sets KonsimentoNumarasiField
        /// </summary>
        [DataMember(Name = "konsimentoNumarasiField", EmitDefaultValue = true)]
        public string KonsimentoNumarasiField { get; set; }

        /// <summary>
        /// Gets or Sets YuklemeTarihiField
        /// </summary>
        [DataMember(Name = "yuklemeTarihiField", EmitDefaultValue = true)]
        public string YuklemeTarihiField { get; set; }

        /// <summary>
        /// Gets or Sets MuhabirUnvanField
        /// </summary>
        [DataMember(Name = "muhabirUnvanField", EmitDefaultValue = true)]
        public string MuhabirUnvanField { get; set; }

        /// <summary>
        /// Gets or Sets SigortaSirketiUnvanField
        /// </summary>
        [DataMember(Name = "sigortaSirketiUnvanField", EmitDefaultValue = true)]
        public string SigortaSirketiUnvanField { get; set; }

        /// <summary>
        /// Gets or Sets IrsaliyeNumarasiField
        /// </summary>
        [DataMember(Name = "irsaliyeNumarasiField", EmitDefaultValue = true)]
        public string IrsaliyeNumarasiField { get; set; }

        /// <summary>
        /// Gets or Sets IrsaliyeTarihiField
        /// </summary>
        [DataMember(Name = "irsaliyeTarihiField", EmitDefaultValue = true)]
        public string IrsaliyeTarihiField { get; set; }

        /// <summary>
        /// Gets or Sets ImalatciVergiNoField
        /// </summary>
        [DataMember(Name = "imalatciVergiNoField", EmitDefaultValue = true)]
        public string ImalatciVergiNoField { get; set; }

        /// <summary>
        /// Gets or Sets EFaturaHashDegeriField
        /// </summary>
        [DataMember(Name = "eFaturaHashDegeriField", EmitDefaultValue = true)]
        public string EFaturaHashDegeriField { get; set; }

        /// <summary>
        /// Gets or Sets FaturaXmlField
        /// </summary>
        [DataMember(Name = "faturaXmlField", EmitDefaultValue = true)]
        public byte[] FaturaXmlField { get; set; }

        /// <summary>
        /// Gets or Sets FaturamParaIdField
        /// </summary>
        [DataMember(Name = "faturamParaIdField", EmitDefaultValue = true)]
        public string FaturamParaIdField { get; set; }

        /// <summary>
        /// Gets or Sets AliciNeviKimlikTipField
        /// </summary>
        [DataMember(Name = "aliciNeviKimlikTipField", EmitDefaultValue = true)]
        public string AliciNeviKimlikTipField { get; set; }

        /// <summary>
        /// Gets or Sets AliciNeviKimlikNoField
        /// </summary>
        [DataMember(Name = "aliciNeviKimlikNoField", EmitDefaultValue = true)]
        public string AliciNeviKimlikNoField { get; set; }

        /// <summary>
        /// Gets or Sets SaticiNeviKimlikTipField
        /// </summary>
        [DataMember(Name = "saticiNeviKimlikTipField", EmitDefaultValue = true)]
        public string SaticiNeviKimlikTipField { get; set; }

        /// <summary>
        /// Gets or Sets SaticiNeviKimlikNoField
        /// </summary>
        [DataMember(Name = "saticiNeviKimlikNoField", EmitDefaultValue = true)]
        public string SaticiNeviKimlikNoField { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DevirGuncelleFaturaEkGirdiParametre {\n");
            sb.Append("  GumrukBeyannameNoField: ").Append(GumrukBeyannameNoField).Append("\n");
            sb.Append("  KonsimentoNumarasiField: ").Append(KonsimentoNumarasiField).Append("\n");
            sb.Append("  YuklemeTarihiField: ").Append(YuklemeTarihiField).Append("\n");
            sb.Append("  MuhabirUnvanField: ").Append(MuhabirUnvanField).Append("\n");
            sb.Append("  SigortaSirketiUnvanField: ").Append(SigortaSirketiUnvanField).Append("\n");
            sb.Append("  IrsaliyeNumarasiField: ").Append(IrsaliyeNumarasiField).Append("\n");
            sb.Append("  IrsaliyeTarihiField: ").Append(IrsaliyeTarihiField).Append("\n");
            sb.Append("  ImalatciVergiNoField: ").Append(ImalatciVergiNoField).Append("\n");
            sb.Append("  EFaturaHashDegeriField: ").Append(EFaturaHashDegeriField).Append("\n");
            sb.Append("  FaturaXmlField: ").Append(FaturaXmlField).Append("\n");
            sb.Append("  FaturamParaIdField: ").Append(FaturamParaIdField).Append("\n");
            sb.Append("  AliciNeviKimlikTipField: ").Append(AliciNeviKimlikTipField).Append("\n");
            sb.Append("  AliciNeviKimlikNoField: ").Append(AliciNeviKimlikNoField).Append("\n");
            sb.Append("  SaticiNeviKimlikTipField: ").Append(SaticiNeviKimlikTipField).Append("\n");
            sb.Append("  SaticiNeviKimlikNoField: ").Append(SaticiNeviKimlikNoField).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
