/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// EslemeParametre
    /// </summary>
    [DataContract(Name = "EslemeParametre")]
    public partial class EslemeParametre : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EslemeParametre" /> class.
        /// </summary>
        /// <param name="siraNoField">siraNoField.</param>
        /// <param name="bazBelgeEslemeTutariField">bazBelgeEslemeTutariField.</param>
        /// <param name="eslenenBelgeReferansNoField">eslenenBelgeReferansNoField.</param>
        /// <param name="eslenenBelgeEslemeTutariField">eslenenBelgeEslemeTutariField.</param>
        public EslemeParametre(string siraNoField = default(string), double bazBelgeEslemeTutariField = default(double), string eslenenBelgeReferansNoField = default(string), double eslenenBelgeEslemeTutariField = default(double))
        {
            this.SiraNoField = siraNoField;
            this.BazBelgeEslemeTutariField = bazBelgeEslemeTutariField;
            this.EslenenBelgeReferansNoField = eslenenBelgeReferansNoField;
            this.EslenenBelgeEslemeTutariField = eslenenBelgeEslemeTutariField;
        }

        /// <summary>
        /// Gets or Sets SiraNoField
        /// </summary>
        [DataMember(Name = "siraNoField", EmitDefaultValue = true)]
        public string SiraNoField { get; set; }

        /// <summary>
        /// Gets or Sets BazBelgeEslemeTutariField
        /// </summary>
        [DataMember(Name = "bazBelgeEslemeTutariField", EmitDefaultValue = false)]
        public double BazBelgeEslemeTutariField { get; set; }

        /// <summary>
        /// Gets or Sets EslenenBelgeReferansNoField
        /// </summary>
        [DataMember(Name = "eslenenBelgeReferansNoField", EmitDefaultValue = true)]
        public string EslenenBelgeReferansNoField { get; set; }

        /// <summary>
        /// Gets or Sets EslenenBelgeEslemeTutariField
        /// </summary>
        [DataMember(Name = "eslenenBelgeEslemeTutariField", EmitDefaultValue = false)]
        public double EslenenBelgeEslemeTutariField { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EslemeParametre {\n");
            sb.Append("  SiraNoField: ").Append(SiraNoField).Append("\n");
            sb.Append("  BazBelgeEslemeTutariField: ").Append(BazBelgeEslemeTutariField).Append("\n");
            sb.Append("  EslenenBelgeReferansNoField: ").Append(EslenenBelgeReferansNoField).Append("\n");
            sb.Append("  EslenenBelgeEslemeTutariField: ").Append(EslenenBelgeEslemeTutariField).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
