/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// EsnafBilgileri
    /// </summary>
    [DataContract(Name = "EsnafBilgileri")]
    public partial class EsnafBilgileri : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EsnafBilgileri" /> class.
        /// </summary>
        /// <param name="sicilAktifMi">sicilAktifMi.</param>
        /// <param name="baslamaTarihi">baslamaTarihi.</param>
        /// <param name="bitisTarihi">bitisTarihi.</param>
        /// <param name="sicilNo">sicilNo.</param>
        /// <param name="vergiNo">vergiNo.</param>
        /// <param name="odaListesi">odaListesi.</param>
        public EsnafBilgileri(string sicilAktifMi = default(string), string baslamaTarihi = default(string), string bitisTarihi = default(string), string sicilNo = default(string), string vergiNo = default(string), List<OdaBilgileri> odaListesi = default(List<OdaBilgileri>))
        {
            this.SicilAktifMi = sicilAktifMi;
            this.BaslamaTarihi = baslamaTarihi;
            this.BitisTarihi = bitisTarihi;
            this.SicilNo = sicilNo;
            this.VergiNo = vergiNo;
            this.OdaListesi = odaListesi;
        }

        /// <summary>
        /// Gets or Sets SicilAktifMi
        /// </summary>
        [DataMember(Name = "sicilAktifMi", EmitDefaultValue = true)]
        public string SicilAktifMi { get; set; }

        /// <summary>
        /// Gets or Sets BaslamaTarihi
        /// </summary>
        [DataMember(Name = "baslamaTarihi", EmitDefaultValue = true)]
        public string BaslamaTarihi { get; set; }

        /// <summary>
        /// Gets or Sets BitisTarihi
        /// </summary>
        [DataMember(Name = "bitisTarihi", EmitDefaultValue = true)]
        public string BitisTarihi { get; set; }

        /// <summary>
        /// Gets or Sets SicilNo
        /// </summary>
        [DataMember(Name = "sicilNo", EmitDefaultValue = true)]
        public string SicilNo { get; set; }

        /// <summary>
        /// Gets or Sets VergiNo
        /// </summary>
        [DataMember(Name = "vergiNo", EmitDefaultValue = true)]
        public string VergiNo { get; set; }

        /// <summary>
        /// Gets or Sets OdaListesi
        /// </summary>
        [DataMember(Name = "odaListesi", EmitDefaultValue = true)]
        public List<OdaBilgileri> OdaListesi { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EsnafBilgileri {\n");
            sb.Append("  SicilAktifMi: ").Append(SicilAktifMi).Append("\n");
            sb.Append("  BaslamaTarihi: ").Append(BaslamaTarihi).Append("\n");
            sb.Append("  BitisTarihi: ").Append(BitisTarihi).Append("\n");
            sb.Append("  SicilNo: ").Append(SicilNo).Append("\n");
            sb.Append("  VergiNo: ").Append(VergiNo).Append("\n");
            sb.Append("  OdaListesi: ").Append(OdaListesi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
