/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ExistingReturnCheque
    /// </summary>
    [DataContract(Name = "ExistingReturnCheque")]
    public partial class ExistingReturnCheque : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExistingReturnCheque" /> class.
        /// </summary>
        /// <param name="kESIDECIADI">kESIDECIADI.</param>
        /// <param name="kESIDETARIHI">kESIDETARIHI.</param>
        /// <param name="tUTAR">tUTAR.</param>
        /// <param name="mUSTERIADISOYADI">mUSTERIADISOYADI.</param>
        /// <param name="cEKGIRISTARIHI">cEKGIRISTARIHI.</param>
        /// <param name="kESIDECIVKN">kESIDECIVKN.</param>
        /// <param name="tAHSILTEMINAT">tAHSILTEMINAT.</param>
        /// <param name="sONCIRANTAVKNTCKN">sONCIRANTAVKNTCKN.</param>
        /// <param name="sONCIRANTAUNVAN">sONCIRANTAUNVAN.</param>
        public ExistingReturnCheque(string kESIDECIADI = default(string), string kESIDETARIHI = default(string), string tUTAR = default(string), string mUSTERIADISOYADI = default(string), string cEKGIRISTARIHI = default(string), string kESIDECIVKN = default(string), string tAHSILTEMINAT = default(string), string sONCIRANTAVKNTCKN = default(string), string sONCIRANTAUNVAN = default(string))
        {
            this.KESIDECIADI = kESIDECIADI;
            this.KESIDETARIHI = kESIDETARIHI;
            this.TUTAR = tUTAR;
            this.MUSTERIADISOYADI = mUSTERIADISOYADI;
            this.CEKGIRISTARIHI = cEKGIRISTARIHI;
            this.KESIDECIVKN = kESIDECIVKN;
            this.TAHSILTEMINAT = tAHSILTEMINAT;
            this.SONCIRANTAVKNTCKN = sONCIRANTAVKNTCKN;
            this.SONCIRANTAUNVAN = sONCIRANTAUNVAN;
        }

        /// <summary>
        /// Gets or Sets KESIDECIADI
        /// </summary>
        [DataMember(Name = "KESIDECIADI", EmitDefaultValue = true)]
        public string KESIDECIADI { get; set; }

        /// <summary>
        /// Gets or Sets KESIDETARIHI
        /// </summary>
        [DataMember(Name = "KESIDETARIHI", EmitDefaultValue = true)]
        public string KESIDETARIHI { get; set; }

        /// <summary>
        /// Gets or Sets TUTAR
        /// </summary>
        [DataMember(Name = "TUTAR", EmitDefaultValue = true)]
        public string TUTAR { get; set; }

        /// <summary>
        /// Gets or Sets MUSTERIADISOYADI
        /// </summary>
        [DataMember(Name = "MUSTERIADISOYADI", EmitDefaultValue = true)]
        public string MUSTERIADISOYADI { get; set; }

        /// <summary>
        /// Gets or Sets CEKGIRISTARIHI
        /// </summary>
        [DataMember(Name = "CEKGIRISTARIHI", EmitDefaultValue = true)]
        public string CEKGIRISTARIHI { get; set; }

        /// <summary>
        /// Gets or Sets KESIDECIVKN
        /// </summary>
        [DataMember(Name = "KESIDECIVKN", EmitDefaultValue = true)]
        public string KESIDECIVKN { get; set; }

        /// <summary>
        /// Gets or Sets TAHSILTEMINAT
        /// </summary>
        [DataMember(Name = "TAHSILTEMINAT", EmitDefaultValue = true)]
        public string TAHSILTEMINAT { get; set; }

        /// <summary>
        /// Gets or Sets SONCIRANTAVKNTCKN
        /// </summary>
        [DataMember(Name = "SONCIRANTAVKNTCKN", EmitDefaultValue = true)]
        public string SONCIRANTAVKNTCKN { get; set; }

        /// <summary>
        /// Gets or Sets SONCIRANTAUNVAN
        /// </summary>
        [DataMember(Name = "SONCIRANTAUNVAN", EmitDefaultValue = true)]
        public string SONCIRANTAUNVAN { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExistingReturnCheque {\n");
            sb.Append("  KESIDECIADI: ").Append(KESIDECIADI).Append("\n");
            sb.Append("  KESIDETARIHI: ").Append(KESIDETARIHI).Append("\n");
            sb.Append("  TUTAR: ").Append(TUTAR).Append("\n");
            sb.Append("  MUSTERIADISOYADI: ").Append(MUSTERIADISOYADI).Append("\n");
            sb.Append("  CEKGIRISTARIHI: ").Append(CEKGIRISTARIHI).Append("\n");
            sb.Append("  KESIDECIVKN: ").Append(KESIDECIVKN).Append("\n");
            sb.Append("  TAHSILTEMINAT: ").Append(TAHSILTEMINAT).Append("\n");
            sb.Append("  SONCIRANTAVKNTCKN: ").Append(SONCIRANTAVKNTCKN).Append("\n");
            sb.Append("  SONCIRANTAUNVAN: ").Append(SONCIRANTAUNVAN).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
