/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IhtiyatiTedbirliCekResponse
    /// </summary>
    [DataContract(Name = "ihtiyatiTedbirliCekResponse")]
    public partial class IhtiyatiTedbirliCekResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IhtiyatiTedbirliCekResponse" /> class.
        /// </summary>
        /// <param name="ihtCekKurumAdi">ihtCekKurumAdi.</param>
        /// <param name="ihtCekSubeAdi">ihtCekSubeAdi.</param>
        /// <param name="ihtCekSiraNo">ihtCekSiraNo.</param>
        /// <param name="ihtCekIbrazTarihi">ihtCekIbrazTarihi.</param>
        /// <param name="ihtCekTutari">ihtCekTutari.</param>
        /// <param name="ihtOdemeTuru">ihtOdemeTuru.</param>
        /// <param name="ihtCekDurumKodu">ihtCekDurumKodu.</param>
        public IhtiyatiTedbirliCekResponse(string ihtCekKurumAdi = default(string), string ihtCekSubeAdi = default(string), string ihtCekSiraNo = default(string), string ihtCekIbrazTarihi = default(string), double ihtCekTutari = default(double), string ihtOdemeTuru = default(string), string ihtCekDurumKodu = default(string))
        {
            this.IhtCekKurumAdi = ihtCekKurumAdi;
            this.IhtCekSubeAdi = ihtCekSubeAdi;
            this.IhtCekSiraNo = ihtCekSiraNo;
            this.IhtCekIbrazTarihi = ihtCekIbrazTarihi;
            this.IhtCekTutari = ihtCekTutari;
            this.IhtOdemeTuru = ihtOdemeTuru;
            this.IhtCekDurumKodu = ihtCekDurumKodu;
        }

        /// <summary>
        /// Gets or Sets IhtCekKurumAdi
        /// </summary>
        [DataMember(Name = "ihtCekKurumAdi", EmitDefaultValue = true)]
        public string IhtCekKurumAdi { get; set; }

        /// <summary>
        /// Gets or Sets IhtCekSubeAdi
        /// </summary>
        [DataMember(Name = "ihtCekSubeAdi", EmitDefaultValue = true)]
        public string IhtCekSubeAdi { get; set; }

        /// <summary>
        /// Gets or Sets IhtCekSiraNo
        /// </summary>
        [DataMember(Name = "ihtCekSiraNo", EmitDefaultValue = true)]
        public string IhtCekSiraNo { get; set; }

        /// <summary>
        /// Gets or Sets IhtCekIbrazTarihi
        /// </summary>
        [DataMember(Name = "ihtCekIbrazTarihi", EmitDefaultValue = true)]
        public string IhtCekIbrazTarihi { get; set; }

        /// <summary>
        /// Gets or Sets IhtCekTutari
        /// </summary>
        [DataMember(Name = "ihtCekTutari", EmitDefaultValue = false)]
        public double IhtCekTutari { get; set; }

        /// <summary>
        /// Gets or Sets IhtOdemeTuru
        /// </summary>
        [DataMember(Name = "ihtOdemeTuru", EmitDefaultValue = true)]
        public string IhtOdemeTuru { get; set; }

        /// <summary>
        /// Gets or Sets IhtCekDurumKodu
        /// </summary>
        [DataMember(Name = "ihtCekDurumKodu", EmitDefaultValue = true)]
        public string IhtCekDurumKodu { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IhtiyatiTedbirliCekResponse {\n");
            sb.Append("  IhtCekKurumAdi: ").Append(IhtCekKurumAdi).Append("\n");
            sb.Append("  IhtCekSubeAdi: ").Append(IhtCekSubeAdi).Append("\n");
            sb.Append("  IhtCekSiraNo: ").Append(IhtCekSiraNo).Append("\n");
            sb.Append("  IhtCekIbrazTarihi: ").Append(IhtCekIbrazTarihi).Append("\n");
            sb.Append("  IhtCekTutari: ").Append(IhtCekTutari).Append("\n");
            sb.Append("  IhtOdemeTuru: ").Append(IhtOdemeTuru).Append("\n");
            sb.Append("  IhtCekDurumKodu: ").Append(IhtCekDurumKodu).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
