/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IsyeriBilgileri
    /// </summary>
    [DataContract(Name = "IsyeriBilgileri")]
    public partial class IsyeriBilgileri : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IsyeriBilgileri" /> class.
        /// </summary>
        /// <param name="acikAdres">acikAdres.</param>
        /// <param name="isyeriAktifMi">isyeriAktifMi.</param>
        /// <param name="unvan">unvan.</param>
        /// <param name="merkezMi">merkezMi.</param>
        /// <param name="ilAdi">ilAdi.</param>
        /// <param name="ilMernisKodu">ilMernisKodu.</param>
        /// <param name="ilceAdi">ilceAdi.</param>
        /// <param name="ilceMernisKodu">ilceMernisKodu.</param>
        /// <param name="telefon">telefon.</param>
        /// <param name="fax">fax.</param>
        public IsyeriBilgileri(string acikAdres = default(string), string isyeriAktifMi = default(string), string unvan = default(string), string merkezMi = default(string), string ilAdi = default(string), string ilMernisKodu = default(string), string ilceAdi = default(string), string ilceMernisKodu = default(string), string telefon = default(string), string fax = default(string))
        {
            this.AcikAdres = acikAdres;
            this.IsyeriAktifMi = isyeriAktifMi;
            this.Unvan = unvan;
            this.MerkezMi = merkezMi;
            this.IlAdi = ilAdi;
            this.IlMernisKodu = ilMernisKodu;
            this.IlceAdi = ilceAdi;
            this.IlceMernisKodu = ilceMernisKodu;
            this.Telefon = telefon;
            this.Fax = fax;
        }

        /// <summary>
        /// Gets or Sets AcikAdres
        /// </summary>
        [DataMember(Name = "acikAdres", EmitDefaultValue = true)]
        public string AcikAdres { get; set; }

        /// <summary>
        /// Gets or Sets IsyeriAktifMi
        /// </summary>
        [DataMember(Name = "isyeriAktifMi", EmitDefaultValue = true)]
        public string IsyeriAktifMi { get; set; }

        /// <summary>
        /// Gets or Sets Unvan
        /// </summary>
        [DataMember(Name = "unvan", EmitDefaultValue = true)]
        public string Unvan { get; set; }

        /// <summary>
        /// Gets or Sets MerkezMi
        /// </summary>
        [DataMember(Name = "merkezMi", EmitDefaultValue = true)]
        public string MerkezMi { get; set; }

        /// <summary>
        /// Gets or Sets IlAdi
        /// </summary>
        [DataMember(Name = "ilAdi", EmitDefaultValue = true)]
        public string IlAdi { get; set; }

        /// <summary>
        /// Gets or Sets IlMernisKodu
        /// </summary>
        [DataMember(Name = "ilMernisKodu", EmitDefaultValue = true)]
        public string IlMernisKodu { get; set; }

        /// <summary>
        /// Gets or Sets IlceAdi
        /// </summary>
        [DataMember(Name = "ilceAdi", EmitDefaultValue = true)]
        public string IlceAdi { get; set; }

        /// <summary>
        /// Gets or Sets IlceMernisKodu
        /// </summary>
        [DataMember(Name = "ilceMernisKodu", EmitDefaultValue = true)]
        public string IlceMernisKodu { get; set; }

        /// <summary>
        /// Gets or Sets Telefon
        /// </summary>
        [DataMember(Name = "telefon", EmitDefaultValue = true)]
        public string Telefon { get; set; }

        /// <summary>
        /// Gets or Sets Fax
        /// </summary>
        [DataMember(Name = "fax", EmitDefaultValue = true)]
        public string Fax { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IsyeriBilgileri {\n");
            sb.Append("  AcikAdres: ").Append(AcikAdres).Append("\n");
            sb.Append("  IsyeriAktifMi: ").Append(IsyeriAktifMi).Append("\n");
            sb.Append("  Unvan: ").Append(Unvan).Append("\n");
            sb.Append("  MerkezMi: ").Append(MerkezMi).Append("\n");
            sb.Append("  IlAdi: ").Append(IlAdi).Append("\n");
            sb.Append("  IlMernisKodu: ").Append(IlMernisKodu).Append("\n");
            sb.Append("  IlceAdi: ").Append(IlceAdi).Append("\n");
            sb.Append("  IlceMernisKodu: ").Append(IlceMernisKodu).Append("\n");
            sb.Append("  Telefon: ").Append(Telefon).Append("\n");
            sb.Append("  Fax: ").Append(Fax).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
