/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// KKBCommercialRegistrySummaryQueryRequest
    /// </summary>
    [DataContract(Name = "KKBCommercialRegistrySummaryQueryRequest")]
    public partial class KKBCommercialRegistrySummaryQueryRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KKBCommercialRegistrySummaryQueryRequest" /> class.
        /// </summary>
        /// <param name="kurumEftKodu">kurumEftKodu.</param>
        /// <param name="tcKimlikNo">tcKimlikNo.</param>
        /// <param name="vergiKimlikNo">vergiKimlikNo.</param>
        /// <param name="ticariSicilNo">ticariSicilNo.</param>
        /// <param name="tescilIli">tescilIli.</param>
        /// <param name="tescilMerkezi">tescilMerkezi.</param>
        /// <param name="gazeteTarihiBaslangic">gazeteTarihiBaslangic.</param>
        /// <param name="gazeteTarihiBitis">gazeteTarihiBitis.</param>
        /// <param name="ortakKimlikNo">ortakKimlikNo.</param>
        /// <param name="mersisNo">mersisNo.</param>
        public KKBCommercialRegistrySummaryQueryRequest(string kurumEftKodu = default(string), string tcKimlikNo = default(string), string vergiKimlikNo = default(string), int ticariSicilNo = default(int), int tescilIli = default(int), int tescilMerkezi = default(int), string gazeteTarihiBaslangic = default(string), string gazeteTarihiBitis = default(string), string ortakKimlikNo = default(string), string mersisNo = default(string))
        {
            this.KurumEftKodu = kurumEftKodu;
            this.TcKimlikNo = tcKimlikNo;
            this.VergiKimlikNo = vergiKimlikNo;
            this.TicariSicilNo = ticariSicilNo;
            this.TescilIli = tescilIli;
            this.TescilMerkezi = tescilMerkezi;
            this.GazeteTarihiBaslangic = gazeteTarihiBaslangic;
            this.GazeteTarihiBitis = gazeteTarihiBitis;
            this.OrtakKimlikNo = ortakKimlikNo;
            this.MersisNo = mersisNo;
        }

        /// <summary>
        /// Gets or Sets KurumEftKodu
        /// </summary>
        [DataMember(Name = "kurumEftKodu", EmitDefaultValue = true)]
        public string KurumEftKodu { get; set; }

        /// <summary>
        /// Gets or Sets TcKimlikNo
        /// </summary>
        [DataMember(Name = "tcKimlikNo", EmitDefaultValue = true)]
        public string TcKimlikNo { get; set; }

        /// <summary>
        /// Gets or Sets VergiKimlikNo
        /// </summary>
        [DataMember(Name = "vergiKimlikNo", EmitDefaultValue = true)]
        public string VergiKimlikNo { get; set; }

        /// <summary>
        /// Gets or Sets TicariSicilNo
        /// </summary>
        [DataMember(Name = "ticariSicilNo", EmitDefaultValue = false)]
        public int TicariSicilNo { get; set; }

        /// <summary>
        /// Gets or Sets TescilIli
        /// </summary>
        [DataMember(Name = "tescilIli", EmitDefaultValue = false)]
        public int TescilIli { get; set; }

        /// <summary>
        /// Gets or Sets TescilMerkezi
        /// </summary>
        [DataMember(Name = "tescilMerkezi", EmitDefaultValue = false)]
        public int TescilMerkezi { get; set; }

        /// <summary>
        /// Gets or Sets GazeteTarihiBaslangic
        /// </summary>
        [DataMember(Name = "gazeteTarihiBaslangic", EmitDefaultValue = true)]
        public string GazeteTarihiBaslangic { get; set; }

        /// <summary>
        /// Gets or Sets GazeteTarihiBitis
        /// </summary>
        [DataMember(Name = "gazeteTarihiBitis", EmitDefaultValue = true)]
        public string GazeteTarihiBitis { get; set; }

        /// <summary>
        /// Gets or Sets OrtakKimlikNo
        /// </summary>
        [DataMember(Name = "ortakKimlikNo", EmitDefaultValue = true)]
        public string OrtakKimlikNo { get; set; }

        /// <summary>
        /// Gets or Sets MersisNo
        /// </summary>
        [DataMember(Name = "mersisNo", EmitDefaultValue = true)]
        public string MersisNo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KKBCommercialRegistrySummaryQueryRequest {\n");
            sb.Append("  KurumEftKodu: ").Append(KurumEftKodu).Append("\n");
            sb.Append("  TcKimlikNo: ").Append(TcKimlikNo).Append("\n");
            sb.Append("  VergiKimlikNo: ").Append(VergiKimlikNo).Append("\n");
            sb.Append("  TicariSicilNo: ").Append(TicariSicilNo).Append("\n");
            sb.Append("  TescilIli: ").Append(TescilIli).Append("\n");
            sb.Append("  TescilMerkezi: ").Append(TescilMerkezi).Append("\n");
            sb.Append("  GazeteTarihiBaslangic: ").Append(GazeteTarihiBaslangic).Append("\n");
            sb.Append("  GazeteTarihiBitis: ").Append(GazeteTarihiBitis).Append("\n");
            sb.Append("  OrtakKimlikNo: ").Append(OrtakKimlikNo).Append("\n");
            sb.Append("  MersisNo: ").Append(MersisNo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
