/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// KKBRiskRaporuResponse
    /// </summary>
    [DataContract(Name = "KKBRiskRaporuResponse")]
    public partial class KKBRiskRaporuResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KKBRiskRaporuResponse" /> class.
        /// </summary>
        /// <param name="errors">errors.</param>
        /// <param name="riskRaporuBkBilgi">riskRaporuBkBilgi.</param>
        /// <param name="riskRaporuBkHesapDokumu">riskRaporuBkHesapDokumu.</param>
        /// <param name="riskRaporuBorcluTeminat">riskRaporuBorcluTeminat.</param>
        /// <param name="riskRaporuKefilTeminatBilgi">riskRaporuKefilTeminatBilgi.</param>
        /// <param name="riskRaporuKlkrList">riskRaporuKlkrList.</param>
        /// <param name="riskRaporuTicariVysBilgi">riskRaporuTicariVysBilgi.</param>
        /// <param name="riskRaporuTkBilgi">riskRaporuTkBilgi.</param>
        /// <param name="riskRaporuVysBilgi">riskRaporuVysBilgi.</param>
        /// <param name="riskRaporuLimitRiskDokum">riskRaporuLimitRiskDokum.</param>
        /// <param name="riskRaporuBknBilgi">riskRaporuBknBilgi.</param>
        public KKBRiskRaporuResponse(IslemResponse errors = default(IslemResponse), List<RiskRaporuBkBilgi> riskRaporuBkBilgi = default(List<RiskRaporuBkBilgi>), List<RiskRaporuBkHesapDokumu> riskRaporuBkHesapDokumu = default(List<RiskRaporuBkHesapDokumu>), List<RiskRaporuBorcluTeminat> riskRaporuBorcluTeminat = default(List<RiskRaporuBorcluTeminat>), List<RiskRaporuKefilTeminatBilgi> riskRaporuKefilTeminatBilgi = default(List<RiskRaporuKefilTeminatBilgi>), List<RiskRaporuKlkrList> riskRaporuKlkrList = default(List<RiskRaporuKlkrList>), List<RiskRaporuTicariVysBilgi> riskRaporuTicariVysBilgi = default(List<RiskRaporuTicariVysBilgi>), List<RiskRaporuTkBilgi> riskRaporuTkBilgi = default(List<RiskRaporuTkBilgi>), List<RiskRaporuVysBilgi> riskRaporuVysBilgi = default(List<RiskRaporuVysBilgi>), List<RiskRaporuLimitRiskDokum> riskRaporuLimitRiskDokum = default(List<RiskRaporuLimitRiskDokum>), List<RiskRaporuBknBilgi> riskRaporuBknBilgi = default(List<RiskRaporuBknBilgi>))
        {
            this.Errors = errors;
            this.RiskRaporuBkBilgi = riskRaporuBkBilgi;
            this.RiskRaporuBkHesapDokumu = riskRaporuBkHesapDokumu;
            this.RiskRaporuBorcluTeminat = riskRaporuBorcluTeminat;
            this.RiskRaporuKefilTeminatBilgi = riskRaporuKefilTeminatBilgi;
            this.RiskRaporuKlkrList = riskRaporuKlkrList;
            this.RiskRaporuTicariVysBilgi = riskRaporuTicariVysBilgi;
            this.RiskRaporuTkBilgi = riskRaporuTkBilgi;
            this.RiskRaporuVysBilgi = riskRaporuVysBilgi;
            this.RiskRaporuLimitRiskDokum = riskRaporuLimitRiskDokum;
            this.RiskRaporuBknBilgi = riskRaporuBknBilgi;
        }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public IslemResponse Errors { get; set; }

        /// <summary>
        /// Gets or Sets RiskRaporuBkBilgi
        /// </summary>
        [DataMember(Name = "riskRaporuBkBilgi", EmitDefaultValue = true)]
        public List<RiskRaporuBkBilgi> RiskRaporuBkBilgi { get; set; }

        /// <summary>
        /// Gets or Sets RiskRaporuBkHesapDokumu
        /// </summary>
        [DataMember(Name = "riskRaporuBkHesapDokumu", EmitDefaultValue = true)]
        public List<RiskRaporuBkHesapDokumu> RiskRaporuBkHesapDokumu { get; set; }

        /// <summary>
        /// Gets or Sets RiskRaporuBorcluTeminat
        /// </summary>
        [DataMember(Name = "riskRaporuBorcluTeminat", EmitDefaultValue = true)]
        public List<RiskRaporuBorcluTeminat> RiskRaporuBorcluTeminat { get; set; }

        /// <summary>
        /// Gets or Sets RiskRaporuKefilTeminatBilgi
        /// </summary>
        [DataMember(Name = "riskRaporuKefilTeminatBilgi", EmitDefaultValue = true)]
        public List<RiskRaporuKefilTeminatBilgi> RiskRaporuKefilTeminatBilgi { get; set; }

        /// <summary>
        /// Gets or Sets RiskRaporuKlkrList
        /// </summary>
        [DataMember(Name = "riskRaporuKlkrList", EmitDefaultValue = true)]
        public List<RiskRaporuKlkrList> RiskRaporuKlkrList { get; set; }

        /// <summary>
        /// Gets or Sets RiskRaporuTicariVysBilgi
        /// </summary>
        [DataMember(Name = "riskRaporuTicariVysBilgi", EmitDefaultValue = true)]
        public List<RiskRaporuTicariVysBilgi> RiskRaporuTicariVysBilgi { get; set; }

        /// <summary>
        /// Gets or Sets RiskRaporuTkBilgi
        /// </summary>
        [DataMember(Name = "riskRaporuTkBilgi", EmitDefaultValue = true)]
        public List<RiskRaporuTkBilgi> RiskRaporuTkBilgi { get; set; }

        /// <summary>
        /// Gets or Sets RiskRaporuVysBilgi
        /// </summary>
        [DataMember(Name = "riskRaporuVysBilgi", EmitDefaultValue = true)]
        public List<RiskRaporuVysBilgi> RiskRaporuVysBilgi { get; set; }

        /// <summary>
        /// Gets or Sets RiskRaporuLimitRiskDokum
        /// </summary>
        [DataMember(Name = "riskRaporuLimitRiskDokum", EmitDefaultValue = true)]
        public List<RiskRaporuLimitRiskDokum> RiskRaporuLimitRiskDokum { get; set; }

        /// <summary>
        /// Gets or Sets RiskRaporuBknBilgi
        /// </summary>
        [DataMember(Name = "riskRaporuBknBilgi", EmitDefaultValue = true)]
        public List<RiskRaporuBknBilgi> RiskRaporuBknBilgi { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KKBRiskRaporuResponse {\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  RiskRaporuBkBilgi: ").Append(RiskRaporuBkBilgi).Append("\n");
            sb.Append("  RiskRaporuBkHesapDokumu: ").Append(RiskRaporuBkHesapDokumu).Append("\n");
            sb.Append("  RiskRaporuBorcluTeminat: ").Append(RiskRaporuBorcluTeminat).Append("\n");
            sb.Append("  RiskRaporuKefilTeminatBilgi: ").Append(RiskRaporuKefilTeminatBilgi).Append("\n");
            sb.Append("  RiskRaporuKlkrList: ").Append(RiskRaporuKlkrList).Append("\n");
            sb.Append("  RiskRaporuTicariVysBilgi: ").Append(RiskRaporuTicariVysBilgi).Append("\n");
            sb.Append("  RiskRaporuTkBilgi: ").Append(RiskRaporuTkBilgi).Append("\n");
            sb.Append("  RiskRaporuVysBilgi: ").Append(RiskRaporuVysBilgi).Append("\n");
            sb.Append("  RiskRaporuLimitRiskDokum: ").Append(RiskRaporuLimitRiskDokum).Append("\n");
            sb.Append("  RiskRaporuBknBilgi: ").Append(RiskRaporuBknBilgi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
