/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// KKBSummaryResponse
    /// </summary>
    [DataContract(Name = "KKBSummaryResponse")]
    public partial class KKBSummaryResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KKBSummaryResponse" /> class.
        /// </summary>
        /// <param name="data">data.</param>
        /// <param name="errors">errors.</param>
        /// <param name="acikkredidata">acikkredidata.</param>
        /// <param name="kapalikredidata">kapalikredidata.</param>
        /// <param name="acikkmhkkdata">acikkmhkkdata.</param>
        /// <param name="kapalikmhkkdata">kapalikmhkkdata.</param>
        /// <param name="vysdata">vysdata.</param>
        /// <param name="automaticallyResult">automaticallyResult.</param>
        public KKBSummaryResponse(IndKKBData data = default(IndKKBData), IslemResponse errors = default(IslemResponse), AcikKrediData acikkredidata = default(AcikKrediData), KapaliKrediData kapalikredidata = default(KapaliKrediData), AcikKMHKKData acikkmhkkdata = default(AcikKMHKKData), KapaliKMHKKData kapalikmhkkdata = default(KapaliKMHKKData), VYSData vysdata = default(VYSData), string automaticallyResult = default(string))
        {
            this.Data = data;
            this.Errors = errors;
            this.Acikkredidata = acikkredidata;
            this.Kapalikredidata = kapalikredidata;
            this.Acikkmhkkdata = acikkmhkkdata;
            this.Kapalikmhkkdata = kapalikmhkkdata;
            this.Vysdata = vysdata;
            this.AutomaticallyResult = automaticallyResult;
        }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public IndKKBData Data { get; set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public IslemResponse Errors { get; set; }

        /// <summary>
        /// Gets or Sets Acikkredidata
        /// </summary>
        [DataMember(Name = "acikkredidata", EmitDefaultValue = false)]
        public AcikKrediData Acikkredidata { get; set; }

        /// <summary>
        /// Gets or Sets Kapalikredidata
        /// </summary>
        [DataMember(Name = "kapalikredidata", EmitDefaultValue = false)]
        public KapaliKrediData Kapalikredidata { get; set; }

        /// <summary>
        /// Gets or Sets Acikkmhkkdata
        /// </summary>
        [DataMember(Name = "acikkmhkkdata", EmitDefaultValue = false)]
        public AcikKMHKKData Acikkmhkkdata { get; set; }

        /// <summary>
        /// Gets or Sets Kapalikmhkkdata
        /// </summary>
        [DataMember(Name = "kapalikmhkkdata", EmitDefaultValue = false)]
        public KapaliKMHKKData Kapalikmhkkdata { get; set; }

        /// <summary>
        /// Gets or Sets Vysdata
        /// </summary>
        [DataMember(Name = "vysdata", EmitDefaultValue = false)]
        public VYSData Vysdata { get; set; }

        /// <summary>
        /// Gets or Sets AutomaticallyResult
        /// </summary>
        [DataMember(Name = "AutomaticallyResult", EmitDefaultValue = true)]
        public string AutomaticallyResult { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KKBSummaryResponse {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Acikkredidata: ").Append(Acikkredidata).Append("\n");
            sb.Append("  Kapalikredidata: ").Append(Kapalikredidata).Append("\n");
            sb.Append("  Acikkmhkkdata: ").Append(Acikkmhkkdata).Append("\n");
            sb.Append("  Kapalikmhkkdata: ").Append(Kapalikmhkkdata).Append("\n");
            sb.Append("  Vysdata: ").Append(Vysdata).Append("\n");
            sb.Append("  AutomaticallyResult: ").Append(AutomaticallyResult).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
