/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// KlrteServisResponse
    /// </summary>
    [DataContract(Name = "KlrteServisResponse")]
    public partial class KlrteServisResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KlrteServisResponse" /> class.
        /// </summary>
        /// <param name="errors">errors.</param>
        /// <param name="data">data.</param>
        /// <param name="lineack">lineack.</param>
        /// <param name="ilkislem">ilkislem.</param>
        /// <param name="gksack">gksack.</param>
        public KlrteServisResponse(IslemResponse errors = default(IslemResponse), KlrteRestServisResponse data = default(KlrteRestServisResponse), List<Lineacklist> lineack = default(List<Lineacklist>), string ilkislem = default(string), string gksack = default(string))
        {
            this.Errors = errors;
            this.Data = data;
            this.Lineack = lineack;
            this.Ilkislem = ilkislem;
            this.Gksack = gksack;
        }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public IslemResponse Errors { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public KlrteRestServisResponse Data { get; set; }

        /// <summary>
        /// Gets or Sets Lineack
        /// </summary>
        [DataMember(Name = "lineack", EmitDefaultValue = true)]
        public List<Lineacklist> Lineack { get; set; }

        /// <summary>
        /// Gets or Sets Ilkislem
        /// </summary>
        [DataMember(Name = "ilkislem", EmitDefaultValue = true)]
        public string Ilkislem { get; set; }

        /// <summary>
        /// Gets or Sets Gksack
        /// </summary>
        [DataMember(Name = "gksack", EmitDefaultValue = true)]
        public string Gksack { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KlrteServisResponse {\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Lineack: ").Append(Lineack).Append("\n");
            sb.Append("  Ilkislem: ").Append(Ilkislem).Append("\n");
            sb.Append("  Gksack: ").Append(Gksack).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
