/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// MemzucEntResponse
    /// </summary>
    [DataContract(Name = "MemzucEntResponse")]
    public partial class MemzucEntResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MemzucEntResponse" /> class.
        /// </summary>
        /// <param name="unvan">unvan.</param>
        /// <param name="bankasayisi">bankasayisi.</param>
        /// <param name="errors">errors.</param>
        /// <param name="data">data.</param>
        /// <param name="automaticallyResult">automaticallyResult.</param>
        /// <param name="canliFaktoringLimit">canliFaktoringLimit.</param>
        /// <param name="canliFaktoringRisk">canliFaktoringRisk.</param>
        /// <param name="takipToplamLimit">takipToplamLimit.</param>
        /// <param name="takipSayi">takipSayi.</param>
        public MemzucEntResponse(string unvan = default(string), string bankasayisi = default(string), IslemResponse errors = default(IslemResponse), List<MemzucEntResult> data = default(List<MemzucEntResult>), string automaticallyResult = default(string), double canliFaktoringLimit = default(double), double canliFaktoringRisk = default(double), double takipToplamLimit = default(double), int takipSayi = default(int))
        {
            this.Unvan = unvan;
            this.Bankasayisi = bankasayisi;
            this.Errors = errors;
            this.Data = data;
            this.AutomaticallyResult = automaticallyResult;
            this.CanliFaktoringLimit = canliFaktoringLimit;
            this.CanliFaktoringRisk = canliFaktoringRisk;
            this.TakipToplamLimit = takipToplamLimit;
            this.TakipSayi = takipSayi;
        }

        /// <summary>
        /// Gets or Sets Unvan
        /// </summary>
        [DataMember(Name = "unvan", EmitDefaultValue = true)]
        public string Unvan { get; set; }

        /// <summary>
        /// Gets or Sets Bankasayisi
        /// </summary>
        [DataMember(Name = "bankasayisi", EmitDefaultValue = true)]
        public string Bankasayisi { get; set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public IslemResponse Errors { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = true)]
        public List<MemzucEntResult> Data { get; set; }

        /// <summary>
        /// Gets or Sets AutomaticallyResult
        /// </summary>
        [DataMember(Name = "AutomaticallyResult", EmitDefaultValue = true)]
        public string AutomaticallyResult { get; set; }

        /// <summary>
        /// Gets or Sets CanliFaktoringLimit
        /// </summary>
        [DataMember(Name = "canliFaktoringLimit", EmitDefaultValue = false)]
        public double CanliFaktoringLimit { get; set; }

        /// <summary>
        /// Gets or Sets CanliFaktoringRisk
        /// </summary>
        [DataMember(Name = "canliFaktoringRisk", EmitDefaultValue = false)]
        public double CanliFaktoringRisk { get; set; }

        /// <summary>
        /// Gets or Sets TakipToplamLimit
        /// </summary>
        [DataMember(Name = "takipToplamLimit", EmitDefaultValue = false)]
        public double TakipToplamLimit { get; set; }

        /// <summary>
        /// Gets or Sets TakipSayi
        /// </summary>
        [DataMember(Name = "takipSayi", EmitDefaultValue = false)]
        public int TakipSayi { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MemzucEntResponse {\n");
            sb.Append("  Unvan: ").Append(Unvan).Append("\n");
            sb.Append("  Bankasayisi: ").Append(Bankasayisi).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  AutomaticallyResult: ").Append(AutomaticallyResult).Append("\n");
            sb.Append("  CanliFaktoringLimit: ").Append(CanliFaktoringLimit).Append("\n");
            sb.Append("  CanliFaktoringRisk: ").Append(CanliFaktoringRisk).Append("\n");
            sb.Append("  TakipToplamLimit: ").Append(TakipToplamLimit).Append("\n");
            sb.Append("  TakipSayi: ").Append(TakipSayi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
