/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// MersisRequestResultResponse
    /// </summary>
    [DataContract(Name = "MersisRequestResultResponse")]
    public partial class MersisRequestResultResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MersisRequestResultResponse" /> class.
        /// </summary>
        /// <param name="islemSonucu">islemSonucu.</param>
        /// <param name="hataAciklama">hataAciklama.</param>
        /// <param name="durumKodu">durumKodu.</param>
        /// <param name="durumKoduAciklamasi">durumKoduAciklamasi.</param>
        /// <param name="referansNo">referansNo.</param>
        /// <param name="vergiNo">vergiNo.</param>
        /// <param name="tcKimlikNo">tcKimlikNo.</param>
        /// <param name="mersisNo">mersisNo.</param>
        /// <param name="firmaListesi">firmaListesi.</param>
        public MersisRequestResultResponse(string islemSonucu = default(string), string hataAciklama = default(string), string durumKodu = default(string), string durumKoduAciklamasi = default(string), string referansNo = default(string), string vergiNo = default(string), string tcKimlikNo = default(string), string mersisNo = default(string), List<FirmaBilgileri> firmaListesi = default(List<FirmaBilgileri>))
        {
            this.IslemSonucu = islemSonucu;
            this.HataAciklama = hataAciklama;
            this.DurumKodu = durumKodu;
            this.DurumKoduAciklamasi = durumKoduAciklamasi;
            this.ReferansNo = referansNo;
            this.VergiNo = vergiNo;
            this.TcKimlikNo = tcKimlikNo;
            this.MersisNo = mersisNo;
            this.FirmaListesi = firmaListesi;
        }

        /// <summary>
        /// Gets or Sets IslemSonucu
        /// </summary>
        [DataMember(Name = "islemSonucu", EmitDefaultValue = true)]
        public string IslemSonucu { get; set; }

        /// <summary>
        /// Gets or Sets HataAciklama
        /// </summary>
        [DataMember(Name = "hataAciklama", EmitDefaultValue = true)]
        public string HataAciklama { get; set; }

        /// <summary>
        /// Gets or Sets DurumKodu
        /// </summary>
        [DataMember(Name = "durumKodu", EmitDefaultValue = true)]
        public string DurumKodu { get; set; }

        /// <summary>
        /// Gets or Sets DurumKoduAciklamasi
        /// </summary>
        [DataMember(Name = "durumKoduAciklamasi", EmitDefaultValue = true)]
        public string DurumKoduAciklamasi { get; set; }

        /// <summary>
        /// Gets or Sets ReferansNo
        /// </summary>
        [DataMember(Name = "referansNo", EmitDefaultValue = true)]
        public string ReferansNo { get; set; }

        /// <summary>
        /// Gets or Sets VergiNo
        /// </summary>
        [DataMember(Name = "vergiNo", EmitDefaultValue = true)]
        public string VergiNo { get; set; }

        /// <summary>
        /// Gets or Sets TcKimlikNo
        /// </summary>
        [DataMember(Name = "tcKimlikNo", EmitDefaultValue = true)]
        public string TcKimlikNo { get; set; }

        /// <summary>
        /// Gets or Sets MersisNo
        /// </summary>
        [DataMember(Name = "mersisNo", EmitDefaultValue = true)]
        public string MersisNo { get; set; }

        /// <summary>
        /// Gets or Sets FirmaListesi
        /// </summary>
        [DataMember(Name = "firmaListesi", EmitDefaultValue = true)]
        public List<FirmaBilgileri> FirmaListesi { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MersisRequestResultResponse {\n");
            sb.Append("  IslemSonucu: ").Append(IslemSonucu).Append("\n");
            sb.Append("  HataAciklama: ").Append(HataAciklama).Append("\n");
            sb.Append("  DurumKodu: ").Append(DurumKodu).Append("\n");
            sb.Append("  DurumKoduAciklamasi: ").Append(DurumKoduAciklamasi).Append("\n");
            sb.Append("  ReferansNo: ").Append(ReferansNo).Append("\n");
            sb.Append("  VergiNo: ").Append(VergiNo).Append("\n");
            sb.Append("  TcKimlikNo: ").Append(TcKimlikNo).Append("\n");
            sb.Append("  MersisNo: ").Append(MersisNo).Append("\n");
            sb.Append("  FirmaListesi: ").Append(FirmaListesi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
