/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// MfksProformaFaturaBean
    /// </summary>
    [DataContract(Name = "MfksProformaFaturaBean")]
    public partial class MfksProformaFaturaBean : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MfksProformaFaturaBean" /> class.
        /// </summary>
        /// <param name="odemeSartlari">odemeSartlari.</param>
        /// <param name="teslimTarihi">teslimTarihi.</param>
        /// <param name="muhtemelFaturaKesimTarihi">muhtemelFaturaKesimTarihi.</param>
        /// <param name="tahsilatBeklentiTarihi">tahsilatBeklentiTarihi.</param>
        public MfksProformaFaturaBean(string odemeSartlari = default(string), string teslimTarihi = default(string), string muhtemelFaturaKesimTarihi = default(string), string tahsilatBeklentiTarihi = default(string))
        {
            this.OdemeSartlari = odemeSartlari;
            this.TeslimTarihi = teslimTarihi;
            this.MuhtemelFaturaKesimTarihi = muhtemelFaturaKesimTarihi;
            this.TahsilatBeklentiTarihi = tahsilatBeklentiTarihi;
        }

        /// <summary>
        /// Gets or Sets OdemeSartlari
        /// </summary>
        [DataMember(Name = "odemeSartlari", EmitDefaultValue = true)]
        public string OdemeSartlari { get; set; }

        /// <summary>
        /// Gets or Sets TeslimTarihi
        /// </summary>
        [DataMember(Name = "teslimTarihi", EmitDefaultValue = true)]
        public string TeslimTarihi { get; set; }

        /// <summary>
        /// Gets or Sets MuhtemelFaturaKesimTarihi
        /// </summary>
        [DataMember(Name = "muhtemelFaturaKesimTarihi", EmitDefaultValue = true)]
        public string MuhtemelFaturaKesimTarihi { get; set; }

        /// <summary>
        /// Gets or Sets TahsilatBeklentiTarihi
        /// </summary>
        [DataMember(Name = "tahsilatBeklentiTarihi", EmitDefaultValue = true)]
        public string TahsilatBeklentiTarihi { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MfksProformaFaturaBean {\n");
            sb.Append("  OdemeSartlari: ").Append(OdemeSartlari).Append("\n");
            sb.Append("  TeslimTarihi: ").Append(TeslimTarihi).Append("\n");
            sb.Append("  MuhtemelFaturaKesimTarihi: ").Append(MuhtemelFaturaKesimTarihi).Append("\n");
            sb.Append("  TahsilatBeklentiTarihi: ").Append(TahsilatBeklentiTarihi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
