/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RiskRaporuBknBilgi
    /// </summary>
    [DataContract(Name = "RiskRaporuBknBilgi")]
    public partial class RiskRaporuBknBilgi : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RiskRaporuBknBilgi" /> class.
        /// </summary>
        /// <param name="bkKrediNotu">bkKrediNotu.</param>
        /// <param name="bkKrediNotuSebepKodu1">bkKrediNotuSebepKodu1.</param>
        /// <param name="bkKrediNotuSebepKodu2">bkKrediNotuSebepKodu2.</param>
        /// <param name="bkKrediNotuSebepKodu3">bkKrediNotuSebepKodu3.</param>
        /// <param name="bkKrediNotuSebepKodu4">bkKrediNotuSebepKodu4.</param>
        /// <param name="bkExclusionCode">bkExclusionCode.</param>
        public RiskRaporuBknBilgi(string bkKrediNotu = default(string), string bkKrediNotuSebepKodu1 = default(string), string bkKrediNotuSebepKodu2 = default(string), string bkKrediNotuSebepKodu3 = default(string), string bkKrediNotuSebepKodu4 = default(string), string bkExclusionCode = default(string))
        {
            this.BkKrediNotu = bkKrediNotu;
            this.BkKrediNotuSebepKodu1 = bkKrediNotuSebepKodu1;
            this.BkKrediNotuSebepKodu2 = bkKrediNotuSebepKodu2;
            this.BkKrediNotuSebepKodu3 = bkKrediNotuSebepKodu3;
            this.BkKrediNotuSebepKodu4 = bkKrediNotuSebepKodu4;
            this.BkExclusionCode = bkExclusionCode;
        }

        /// <summary>
        /// Gets or Sets BkKrediNotu
        /// </summary>
        [DataMember(Name = "bkKrediNotu", EmitDefaultValue = true)]
        public string BkKrediNotu { get; set; }

        /// <summary>
        /// Gets or Sets BkKrediNotuSebepKodu1
        /// </summary>
        [DataMember(Name = "bkKrediNotuSebepKodu1", EmitDefaultValue = true)]
        public string BkKrediNotuSebepKodu1 { get; set; }

        /// <summary>
        /// Gets or Sets BkKrediNotuSebepKodu2
        /// </summary>
        [DataMember(Name = "bkKrediNotuSebepKodu2", EmitDefaultValue = true)]
        public string BkKrediNotuSebepKodu2 { get; set; }

        /// <summary>
        /// Gets or Sets BkKrediNotuSebepKodu3
        /// </summary>
        [DataMember(Name = "bkKrediNotuSebepKodu3", EmitDefaultValue = true)]
        public string BkKrediNotuSebepKodu3 { get; set; }

        /// <summary>
        /// Gets or Sets BkKrediNotuSebepKodu4
        /// </summary>
        [DataMember(Name = "bkKrediNotuSebepKodu4", EmitDefaultValue = true)]
        public string BkKrediNotuSebepKodu4 { get; set; }

        /// <summary>
        /// Gets or Sets BkExclusionCode
        /// </summary>
        [DataMember(Name = "bkExclusionCode", EmitDefaultValue = true)]
        public string BkExclusionCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RiskRaporuBknBilgi {\n");
            sb.Append("  BkKrediNotu: ").Append(BkKrediNotu).Append("\n");
            sb.Append("  BkKrediNotuSebepKodu1: ").Append(BkKrediNotuSebepKodu1).Append("\n");
            sb.Append("  BkKrediNotuSebepKodu2: ").Append(BkKrediNotuSebepKodu2).Append("\n");
            sb.Append("  BkKrediNotuSebepKodu3: ").Append(BkKrediNotuSebepKodu3).Append("\n");
            sb.Append("  BkKrediNotuSebepKodu4: ").Append(BkKrediNotuSebepKodu4).Append("\n");
            sb.Append("  BkExclusionCode: ").Append(BkExclusionCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
