/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RiskRaporuBkHesapDokumu
    /// </summary>
    [DataContract(Name = "RiskRaporuBkHesapDokumu")]
    public partial class RiskRaporuBkHesapDokumu : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RiskRaporuBkHesapDokumu" /> class.
        /// </summary>
        /// <param name="bkAcilisTarihi">bkAcilisTarihi.</param>
        /// <param name="bkDovizKodu">bkDovizKodu.</param>
        /// <param name="bkEnSonGuncellemeTarihi">bkEnSonGuncellemeTarihi.</param>
        /// <param name="bkGecikmedekiBakiye">bkGecikmedekiBakiye.</param>
        /// <param name="bkKapanisTarihi">bkKapanisTarihi.</param>
        /// <param name="bkKayitReferansNo">bkKayitReferansNo.</param>
        /// <param name="bkKrediTuru">bkKrediTuru.</param>
        /// <param name="bkKrediTutariLimiti">bkKrediTutariLimiti.</param>
        /// <param name="bkKurumRumuzu">bkKurumRumuzu.</param>
        /// <param name="bkOdemePerformansiTarihcesi">bkOdemePerformansiTarihcesi.</param>
        /// <param name="bkSiraNo">bkSiraNo.</param>
        /// <param name="bkTakipTarihi">bkTakipTarihi.</param>
        /// <param name="bkToplamBakiye">bkToplamBakiye.</param>
        /// <param name="bkGunlukGecikmeBakiyesi">bkGunlukGecikmeBakiyesi.</param>
        /// <param name="bkGunlukOdemeDurumu">bkGunlukOdemeDurumu.</param>
        /// <param name="bkSorumlulukDurumu">bkSorumlulukDurumu.</param>
        /// <param name="bkTaksitliBakiye">bkTaksitliBakiye.</param>
        /// <param name="bkTaksitSayisi">bkTaksitSayisi.</param>
        /// <param name="bkTaksitTutari">bkTaksitTutari.</param>
        /// <param name="bkOdemeTarihcesiEnOlumsuzDurum">bkOdemeTarihcesiEnOlumsuzDurum.</param>
        /// <param name="bkSonOdemeTutari">bkSonOdemeTutari.</param>
        /// <param name="bkTakibeAlinanBakiye">bkTakibeAlinanBakiye.</param>
        /// <param name="bkZararaAtilmaTarihi">bkZararaAtilmaTarihi.</param>
        /// <param name="bkHesapOzelDurum">bkHesapOzelDurum.</param>
        public RiskRaporuBkHesapDokumu(string bkAcilisTarihi = default(string), string bkDovizKodu = default(string), string bkEnSonGuncellemeTarihi = default(string), string bkGecikmedekiBakiye = default(string), string bkKapanisTarihi = default(string), string bkKayitReferansNo = default(string), string bkKrediTuru = default(string), string bkKrediTutariLimiti = default(string), string bkKurumRumuzu = default(string), string bkOdemePerformansiTarihcesi = default(string), string bkSiraNo = default(string), string bkTakipTarihi = default(string), string bkToplamBakiye = default(string), string bkGunlukGecikmeBakiyesi = default(string), string bkGunlukOdemeDurumu = default(string), string bkSorumlulukDurumu = default(string), string bkTaksitliBakiye = default(string), int bkTaksitSayisi = default(int), string bkTaksitTutari = default(string), string bkOdemeTarihcesiEnOlumsuzDurum = default(string), string bkSonOdemeTutari = default(string), string bkTakibeAlinanBakiye = default(string), string bkZararaAtilmaTarihi = default(string), string bkHesapOzelDurum = default(string))
        {
            this.BkAcilisTarihi = bkAcilisTarihi;
            this.BkDovizKodu = bkDovizKodu;
            this.BkEnSonGuncellemeTarihi = bkEnSonGuncellemeTarihi;
            this.BkGecikmedekiBakiye = bkGecikmedekiBakiye;
            this.BkKapanisTarihi = bkKapanisTarihi;
            this.BkKayitReferansNo = bkKayitReferansNo;
            this.BkKrediTuru = bkKrediTuru;
            this.BkKrediTutariLimiti = bkKrediTutariLimiti;
            this.BkKurumRumuzu = bkKurumRumuzu;
            this.BkOdemePerformansiTarihcesi = bkOdemePerformansiTarihcesi;
            this.BkSiraNo = bkSiraNo;
            this.BkTakipTarihi = bkTakipTarihi;
            this.BkToplamBakiye = bkToplamBakiye;
            this.BkGunlukGecikmeBakiyesi = bkGunlukGecikmeBakiyesi;
            this.BkGunlukOdemeDurumu = bkGunlukOdemeDurumu;
            this.BkSorumlulukDurumu = bkSorumlulukDurumu;
            this.BkTaksitliBakiye = bkTaksitliBakiye;
            this.BkTaksitSayisi = bkTaksitSayisi;
            this.BkTaksitTutari = bkTaksitTutari;
            this.BkOdemeTarihcesiEnOlumsuzDurum = bkOdemeTarihcesiEnOlumsuzDurum;
            this.BkSonOdemeTutari = bkSonOdemeTutari;
            this.BkTakibeAlinanBakiye = bkTakibeAlinanBakiye;
            this.BkZararaAtilmaTarihi = bkZararaAtilmaTarihi;
            this.BkHesapOzelDurum = bkHesapOzelDurum;
        }

        /// <summary>
        /// Gets or Sets BkAcilisTarihi
        /// </summary>
        [DataMember(Name = "bkAcilisTarihi", EmitDefaultValue = true)]
        public string BkAcilisTarihi { get; set; }

        /// <summary>
        /// Gets or Sets BkDovizKodu
        /// </summary>
        [DataMember(Name = "bkDovizKodu", EmitDefaultValue = true)]
        public string BkDovizKodu { get; set; }

        /// <summary>
        /// Gets or Sets BkEnSonGuncellemeTarihi
        /// </summary>
        [DataMember(Name = "bkEnSonGuncellemeTarihi", EmitDefaultValue = true)]
        public string BkEnSonGuncellemeTarihi { get; set; }

        /// <summary>
        /// Gets or Sets BkGecikmedekiBakiye
        /// </summary>
        [DataMember(Name = "bkGecikmedekiBakiye", EmitDefaultValue = true)]
        public string BkGecikmedekiBakiye { get; set; }

        /// <summary>
        /// Gets or Sets BkKapanisTarihi
        /// </summary>
        [DataMember(Name = "bkKapanisTarihi", EmitDefaultValue = true)]
        public string BkKapanisTarihi { get; set; }

        /// <summary>
        /// Gets or Sets BkKayitReferansNo
        /// </summary>
        [DataMember(Name = "bkKayitReferansNo", EmitDefaultValue = true)]
        public string BkKayitReferansNo { get; set; }

        /// <summary>
        /// Gets or Sets BkKrediTuru
        /// </summary>
        [DataMember(Name = "bkKrediTuru", EmitDefaultValue = true)]
        public string BkKrediTuru { get; set; }

        /// <summary>
        /// Gets or Sets BkKrediTutariLimiti
        /// </summary>
        [DataMember(Name = "bkKrediTutariLimiti", EmitDefaultValue = true)]
        public string BkKrediTutariLimiti { get; set; }

        /// <summary>
        /// Gets or Sets BkKurumRumuzu
        /// </summary>
        [DataMember(Name = "bkKurumRumuzu", EmitDefaultValue = true)]
        public string BkKurumRumuzu { get; set; }

        /// <summary>
        /// Gets or Sets BkOdemePerformansiTarihcesi
        /// </summary>
        [DataMember(Name = "bkOdemePerformansiTarihcesi", EmitDefaultValue = true)]
        public string BkOdemePerformansiTarihcesi { get; set; }

        /// <summary>
        /// Gets or Sets BkSiraNo
        /// </summary>
        [DataMember(Name = "bkSiraNo", EmitDefaultValue = true)]
        public string BkSiraNo { get; set; }

        /// <summary>
        /// Gets or Sets BkTakipTarihi
        /// </summary>
        [DataMember(Name = "bkTakipTarihi", EmitDefaultValue = true)]
        public string BkTakipTarihi { get; set; }

        /// <summary>
        /// Gets or Sets BkToplamBakiye
        /// </summary>
        [DataMember(Name = "bkToplamBakiye", EmitDefaultValue = true)]
        public string BkToplamBakiye { get; set; }

        /// <summary>
        /// Gets or Sets BkGunlukGecikmeBakiyesi
        /// </summary>
        [DataMember(Name = "bkGunlukGecikmeBakiyesi", EmitDefaultValue = true)]
        public string BkGunlukGecikmeBakiyesi { get; set; }

        /// <summary>
        /// Gets or Sets BkGunlukOdemeDurumu
        /// </summary>
        [DataMember(Name = "bkGunlukOdemeDurumu", EmitDefaultValue = true)]
        public string BkGunlukOdemeDurumu { get; set; }

        /// <summary>
        /// Gets or Sets BkSorumlulukDurumu
        /// </summary>
        [DataMember(Name = "bkSorumlulukDurumu", EmitDefaultValue = true)]
        public string BkSorumlulukDurumu { get; set; }

        /// <summary>
        /// Gets or Sets BkTaksitliBakiye
        /// </summary>
        [DataMember(Name = "bkTaksitliBakiye", EmitDefaultValue = true)]
        public string BkTaksitliBakiye { get; set; }

        /// <summary>
        /// Gets or Sets BkTaksitSayisi
        /// </summary>
        [DataMember(Name = "bkTaksitSayisi", EmitDefaultValue = false)]
        public int BkTaksitSayisi { get; set; }

        /// <summary>
        /// Gets or Sets BkTaksitTutari
        /// </summary>
        [DataMember(Name = "bkTaksitTutari", EmitDefaultValue = true)]
        public string BkTaksitTutari { get; set; }

        /// <summary>
        /// Gets or Sets BkOdemeTarihcesiEnOlumsuzDurum
        /// </summary>
        [DataMember(Name = "bkOdemeTarihcesiEnOlumsuzDurum", EmitDefaultValue = true)]
        public string BkOdemeTarihcesiEnOlumsuzDurum { get; set; }

        /// <summary>
        /// Gets or Sets BkSonOdemeTutari
        /// </summary>
        [DataMember(Name = "bkSonOdemeTutari", EmitDefaultValue = true)]
        public string BkSonOdemeTutari { get; set; }

        /// <summary>
        /// Gets or Sets BkTakibeAlinanBakiye
        /// </summary>
        [DataMember(Name = "bkTakibeAlinanBakiye", EmitDefaultValue = true)]
        public string BkTakibeAlinanBakiye { get; set; }

        /// <summary>
        /// Gets or Sets BkZararaAtilmaTarihi
        /// </summary>
        [DataMember(Name = "bkZararaAtilmaTarihi", EmitDefaultValue = true)]
        public string BkZararaAtilmaTarihi { get; set; }

        /// <summary>
        /// Gets or Sets BkHesapOzelDurum
        /// </summary>
        [DataMember(Name = "bkHesapOzelDurum", EmitDefaultValue = true)]
        public string BkHesapOzelDurum { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RiskRaporuBkHesapDokumu {\n");
            sb.Append("  BkAcilisTarihi: ").Append(BkAcilisTarihi).Append("\n");
            sb.Append("  BkDovizKodu: ").Append(BkDovizKodu).Append("\n");
            sb.Append("  BkEnSonGuncellemeTarihi: ").Append(BkEnSonGuncellemeTarihi).Append("\n");
            sb.Append("  BkGecikmedekiBakiye: ").Append(BkGecikmedekiBakiye).Append("\n");
            sb.Append("  BkKapanisTarihi: ").Append(BkKapanisTarihi).Append("\n");
            sb.Append("  BkKayitReferansNo: ").Append(BkKayitReferansNo).Append("\n");
            sb.Append("  BkKrediTuru: ").Append(BkKrediTuru).Append("\n");
            sb.Append("  BkKrediTutariLimiti: ").Append(BkKrediTutariLimiti).Append("\n");
            sb.Append("  BkKurumRumuzu: ").Append(BkKurumRumuzu).Append("\n");
            sb.Append("  BkOdemePerformansiTarihcesi: ").Append(BkOdemePerformansiTarihcesi).Append("\n");
            sb.Append("  BkSiraNo: ").Append(BkSiraNo).Append("\n");
            sb.Append("  BkTakipTarihi: ").Append(BkTakipTarihi).Append("\n");
            sb.Append("  BkToplamBakiye: ").Append(BkToplamBakiye).Append("\n");
            sb.Append("  BkGunlukGecikmeBakiyesi: ").Append(BkGunlukGecikmeBakiyesi).Append("\n");
            sb.Append("  BkGunlukOdemeDurumu: ").Append(BkGunlukOdemeDurumu).Append("\n");
            sb.Append("  BkSorumlulukDurumu: ").Append(BkSorumlulukDurumu).Append("\n");
            sb.Append("  BkTaksitliBakiye: ").Append(BkTaksitliBakiye).Append("\n");
            sb.Append("  BkTaksitSayisi: ").Append(BkTaksitSayisi).Append("\n");
            sb.Append("  BkTaksitTutari: ").Append(BkTaksitTutari).Append("\n");
            sb.Append("  BkOdemeTarihcesiEnOlumsuzDurum: ").Append(BkOdemeTarihcesiEnOlumsuzDurum).Append("\n");
            sb.Append("  BkSonOdemeTutari: ").Append(BkSonOdemeTutari).Append("\n");
            sb.Append("  BkTakibeAlinanBakiye: ").Append(BkTakibeAlinanBakiye).Append("\n");
            sb.Append("  BkZararaAtilmaTarihi: ").Append(BkZararaAtilmaTarihi).Append("\n");
            sb.Append("  BkHesapOzelDurum: ").Append(BkHesapOzelDurum).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
