/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TCMBData
    /// </summary>
    [DataContract(Name = "TCMBData")]
    public partial class TCMBData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TCMBData" /> class.
        /// </summary>
        /// <param name="tCKN">tCKN.</param>
        /// <param name="vKN">vKN.</param>
        /// <param name="unvan">unvan.</param>
        /// <param name="tur">tur.</param>
        /// <param name="durum">durum.</param>
        /// <param name="adet1">adet1.</param>
        /// <param name="tutar1">tutar1.</param>
        /// <param name="adet2">adet2.</param>
        /// <param name="tutar2">tutar2.</param>
        /// <param name="adet3">adet3.</param>
        /// <param name="tutar3">tutar3.</param>
        /// <param name="adet4">adet4.</param>
        /// <param name="tutar4">tutar4.</param>
        /// <param name="adet5">adet5.</param>
        /// <param name="tutar5">tutar5.</param>
        /// <param name="adet6">adet6.</param>
        /// <param name="tutar6">tutar6.</param>
        /// <param name="toplamAdet">toplamAdet.</param>
        /// <param name="toplamTutar">toplamTutar.</param>
        public TCMBData(string tCKN = default(string), string vKN = default(string), string unvan = default(string), string tur = default(string), string durum = default(string), string adet1 = default(string), string tutar1 = default(string), string adet2 = default(string), string tutar2 = default(string), string adet3 = default(string), string tutar3 = default(string), string adet4 = default(string), string tutar4 = default(string), string adet5 = default(string), string tutar5 = default(string), string adet6 = default(string), string tutar6 = default(string), string toplamAdet = default(string), string toplamTutar = default(string))
        {
            this.TCKN = tCKN;
            this.VKN = vKN;
            this.Unvan = unvan;
            this.Tur = tur;
            this.Durum = durum;
            this.Adet1 = adet1;
            this.Tutar1 = tutar1;
            this.Adet2 = adet2;
            this.Tutar2 = tutar2;
            this.Adet3 = adet3;
            this.Tutar3 = tutar3;
            this.Adet4 = adet4;
            this.Tutar4 = tutar4;
            this.Adet5 = adet5;
            this.Tutar5 = tutar5;
            this.Adet6 = adet6;
            this.Tutar6 = tutar6;
            this.ToplamAdet = toplamAdet;
            this.ToplamTutar = toplamTutar;
        }

        /// <summary>
        /// Gets or Sets TCKN
        /// </summary>
        [DataMember(Name = "TCKN", EmitDefaultValue = true)]
        public string TCKN { get; set; }

        /// <summary>
        /// Gets or Sets VKN
        /// </summary>
        [DataMember(Name = "VKN", EmitDefaultValue = true)]
        public string VKN { get; set; }

        /// <summary>
        /// Gets or Sets Unvan
        /// </summary>
        [DataMember(Name = "Unvan", EmitDefaultValue = true)]
        public string Unvan { get; set; }

        /// <summary>
        /// Gets or Sets Tur
        /// </summary>
        [DataMember(Name = "Tur", EmitDefaultValue = true)]
        public string Tur { get; set; }

        /// <summary>
        /// Gets or Sets Durum
        /// </summary>
        [DataMember(Name = "Durum", EmitDefaultValue = true)]
        public string Durum { get; set; }

        /// <summary>
        /// Gets or Sets Adet1
        /// </summary>
        [DataMember(Name = "Adet1", EmitDefaultValue = true)]
        public string Adet1 { get; set; }

        /// <summary>
        /// Gets or Sets Tutar1
        /// </summary>
        [DataMember(Name = "Tutar1", EmitDefaultValue = true)]
        public string Tutar1 { get; set; }

        /// <summary>
        /// Gets or Sets Adet2
        /// </summary>
        [DataMember(Name = "Adet2", EmitDefaultValue = true)]
        public string Adet2 { get; set; }

        /// <summary>
        /// Gets or Sets Tutar2
        /// </summary>
        [DataMember(Name = "Tutar2", EmitDefaultValue = true)]
        public string Tutar2 { get; set; }

        /// <summary>
        /// Gets or Sets Adet3
        /// </summary>
        [DataMember(Name = "Adet3", EmitDefaultValue = true)]
        public string Adet3 { get; set; }

        /// <summary>
        /// Gets or Sets Tutar3
        /// </summary>
        [DataMember(Name = "Tutar3", EmitDefaultValue = true)]
        public string Tutar3 { get; set; }

        /// <summary>
        /// Gets or Sets Adet4
        /// </summary>
        [DataMember(Name = "Adet4", EmitDefaultValue = true)]
        public string Adet4 { get; set; }

        /// <summary>
        /// Gets or Sets Tutar4
        /// </summary>
        [DataMember(Name = "Tutar4", EmitDefaultValue = true)]
        public string Tutar4 { get; set; }

        /// <summary>
        /// Gets or Sets Adet5
        /// </summary>
        [DataMember(Name = "Adet5", EmitDefaultValue = true)]
        public string Adet5 { get; set; }

        /// <summary>
        /// Gets or Sets Tutar5
        /// </summary>
        [DataMember(Name = "Tutar5", EmitDefaultValue = true)]
        public string Tutar5 { get; set; }

        /// <summary>
        /// Gets or Sets Adet6
        /// </summary>
        [DataMember(Name = "Adet6", EmitDefaultValue = true)]
        public string Adet6 { get; set; }

        /// <summary>
        /// Gets or Sets Tutar6
        /// </summary>
        [DataMember(Name = "Tutar6", EmitDefaultValue = true)]
        public string Tutar6 { get; set; }

        /// <summary>
        /// Gets or Sets ToplamAdet
        /// </summary>
        [DataMember(Name = "ToplamAdet", EmitDefaultValue = true)]
        public string ToplamAdet { get; set; }

        /// <summary>
        /// Gets or Sets ToplamTutar
        /// </summary>
        [DataMember(Name = "ToplamTutar", EmitDefaultValue = true)]
        public string ToplamTutar { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TCMBData {\n");
            sb.Append("  TCKN: ").Append(TCKN).Append("\n");
            sb.Append("  VKN: ").Append(VKN).Append("\n");
            sb.Append("  Unvan: ").Append(Unvan).Append("\n");
            sb.Append("  Tur: ").Append(Tur).Append("\n");
            sb.Append("  Durum: ").Append(Durum).Append("\n");
            sb.Append("  Adet1: ").Append(Adet1).Append("\n");
            sb.Append("  Tutar1: ").Append(Tutar1).Append("\n");
            sb.Append("  Adet2: ").Append(Adet2).Append("\n");
            sb.Append("  Tutar2: ").Append(Tutar2).Append("\n");
            sb.Append("  Adet3: ").Append(Adet3).Append("\n");
            sb.Append("  Tutar3: ").Append(Tutar3).Append("\n");
            sb.Append("  Adet4: ").Append(Adet4).Append("\n");
            sb.Append("  Tutar4: ").Append(Tutar4).Append("\n");
            sb.Append("  Adet5: ").Append(Adet5).Append("\n");
            sb.Append("  Tutar5: ").Append(Tutar5).Append("\n");
            sb.Append("  Adet6: ").Append(Adet6).Append("\n");
            sb.Append("  Tutar6: ").Append(Tutar6).Append("\n");
            sb.Append("  ToplamAdet: ").Append(ToplamAdet).Append("\n");
            sb.Append("  ToplamTutar: ").Append(ToplamTutar).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
