/*
 * Faktoring API - Test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// VadeliCekOzetResponse
    /// </summary>
    [DataContract(Name = "vadeliCekOzetResponse")]
    public partial class VadeliCekOzetResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VadeliCekOzetResponse" /> class.
        /// </summary>
        /// <param name="vadeliCekDonemi">vadeliCekDonemi.</param>
        /// <param name="vadeliToplamCekAdedi">vadeliToplamCekAdedi.</param>
        /// <param name="vadeliToplamCekTutari">vadeliToplamCekTutari.</param>
        public VadeliCekOzetResponse(string vadeliCekDonemi = default(string), string vadeliToplamCekAdedi = default(string), double vadeliToplamCekTutari = default(double))
        {
            this.VadeliCekDonemi = vadeliCekDonemi;
            this.VadeliToplamCekAdedi = vadeliToplamCekAdedi;
            this.VadeliToplamCekTutari = vadeliToplamCekTutari;
        }

        /// <summary>
        /// Gets or Sets VadeliCekDonemi
        /// </summary>
        [DataMember(Name = "vadeliCekDonemi", EmitDefaultValue = true)]
        public string VadeliCekDonemi { get; set; }

        /// <summary>
        /// Gets or Sets VadeliToplamCekAdedi
        /// </summary>
        [DataMember(Name = "vadeliToplamCekAdedi", EmitDefaultValue = true)]
        public string VadeliToplamCekAdedi { get; set; }

        /// <summary>
        /// Gets or Sets VadeliToplamCekTutari
        /// </summary>
        [DataMember(Name = "vadeliToplamCekTutari", EmitDefaultValue = false)]
        public double VadeliToplamCekTutari { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VadeliCekOzetResponse {\n");
            sb.Append("  VadeliCekDonemi: ").Append(VadeliCekDonemi).Append("\n");
            sb.Append("  VadeliToplamCekAdedi: ").Append(VadeliToplamCekAdedi).Append("\n");
            sb.Append("  VadeliToplamCekTutari: ").Append(VadeliToplamCekTutari).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
